//! BM25 ranked search with multi-language stemming support.
//!
//! This module provides:
//! - [`StemLanguage`]: enum of supported stemming languages with [`parse_language`]
//! - [`resolve_language`]: language precedence logic (frontmatter > CLI > config > English)
//! - [`tokenize`]: Unicode-aware tokenization + stemming pipeline
//!
//! Ranked snippet qualification (iteration 283): a body line qualifies when it
//! contains a positive query leaf: any stem alternative of a plain term, a token
//! starting with a `prefix*`, or the complete consecutive stemmed sequence for a
//! quoted phrase. OR accepts any positive side; excluded terms and field terms
//! never supply snippets. Query tokens carry one stem per corpus language
//! (iteration 302); body tokens use the document language, exactly as scoring does.
//! CJK uses the same overlapping bigrams, including single-character unigrams.
//! Frontmatter never qualifies, but raw body code/fence/comment lines do. Phrases
//! spanning lines and title-only hits may therefore have an empty matches array.
//! Within section scope, prioritize the number of distinct positive query tokens
//! present on each qualifying line, then document order, keeping at most three.
//! Snippets keep original text, one-based full-file lines and heading context.
//! - [`Bm25InvertedIndex`]: serializable in-memory BM25 index built from [`DocumentInput`] values

use std::collections::{HashMap, HashSet};

use rust_stemmers::{Algorithm, Stemmer};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Language (generated by macro to keep enum, canonical_name, to_algorithm,
// and parse_language in sync with a single source of truth)
// ---------------------------------------------------------------------------

macro_rules! define_stem_languages {
    ( default = $default:ident; $( $variant:ident => $canonical:literal, $algo:ident; )+ ) => {
        /// A stemming language supported by the [`rust_stemmers`] crate.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum StemLanguage { $( $variant, )+ }

        impl Default for StemLanguage {
            fn default() -> Self { Self::$default }
        }

        impl StemLanguage {
            pub(crate) fn to_algorithm(self) -> Algorithm {
                match self { $( Self::$variant => Algorithm::$algo, )+ }
            }

            /// Returns the lowercase canonical name for this language variant.
            pub fn canonical_name(self) -> &'static str {
                match self { $( Self::$variant => $canonical, )+ }
            }
        }

        /// Parses a language name string (case-insensitive) into a [`StemLanguage`].
        ///
        /// Accepts full names (e.g. "english") or ISO 639-1 codes (e.g. "en").
        /// Returns an error for unrecognised language names.
        pub fn parse_language(s: &str) -> anyhow::Result<StemLanguage> {
            let lower = s.to_lowercase();
            // Try canonical (full) names first.
            match lower.as_str() {
                $( $canonical => return Ok(StemLanguage::$variant), )+
                _ => {}
            }
            // Try ISO 639-1 two-letter codes.
            match iso639_to_canonical(lower.as_str()) {
                Some(lang) => Ok(lang),
                None => anyhow::bail!(
                    "unknown stemming language: {s:?} (use a full name like \"english\" or an ISO 639-1 code like \"en\")"
                ),
            }
        }
    };
}

/// Map ISO 639-1 two-letter codes to [`StemLanguage`] variants.
fn iso639_to_canonical(code: &str) -> Option<StemLanguage> {
    match code {
        "ar" => Some(StemLanguage::Arabic),
        "da" => Some(StemLanguage::Danish),
        "nl" => Some(StemLanguage::Dutch),
        "en" => Some(StemLanguage::English),
        "fi" => Some(StemLanguage::Finnish),
        "fr" => Some(StemLanguage::French),
        "de" => Some(StemLanguage::German),
        "el" => Some(StemLanguage::Greek),
        "hu" => Some(StemLanguage::Hungarian),
        "it" => Some(StemLanguage::Italian),
        "no" | "nb" | "nn" => Some(StemLanguage::Norwegian),
        "pt" => Some(StemLanguage::Portuguese),
        "ro" => Some(StemLanguage::Romanian),
        "ru" => Some(StemLanguage::Russian),
        "es" => Some(StemLanguage::Spanish),
        "sv" => Some(StemLanguage::Swedish),
        "ta" => Some(StemLanguage::Tamil),
        "tr" => Some(StemLanguage::Turkish),
        _ => None,
    }
}

define_stem_languages! {
    default = English;
    Arabic    => "arabic",    Arabic;
    Danish    => "danish",    Danish;
    Dutch     => "dutch",     Dutch;
    English   => "english",   English;
    Finnish   => "finnish",   Finnish;
    French    => "french",    French;
    German    => "german",    German;
    Greek     => "greek",     Greek;
    Hungarian => "hungarian", Hungarian;
    Italian   => "italian",   Italian;
    Norwegian => "norwegian", Norwegian;
    Portuguese => "portuguese", Portuguese;
    Romanian  => "romanian",  Romanian;
    Russian   => "russian",   Russian;
    Spanish   => "spanish",   Spanish;
    Swedish   => "swedish",   Swedish;
    Tamil     => "tamil",     Tamil;
    Turkish   => "turkish",   Turkish;
}

// ---------------------------------------------------------------------------
// Language resolution
// ---------------------------------------------------------------------------

/// Resolves the stemming language from up to three optional sources.
///
/// Priority: `frontmatter_lang` > `cli_lang` > `config_lang` > [`StemLanguage::English`].
///
/// Each source is a language name string; unrecognised values are silently skipped.
pub fn resolve_language(
    frontmatter_lang: Option<&str>,
    cli_lang: Option<&str>,
    config_lang: Option<&str>,
) -> StemLanguage {
    for lang_str in [frontmatter_lang, cli_lang, config_lang]
        .into_iter()
        .flatten()
    {
        if let Ok(lang) = parse_language(lang_str) {
            return lang;
        }
    }
    StemLanguage::default()
}

// ---------------------------------------------------------------------------
// Tokenizer
// ---------------------------------------------------------------------------

/// Create a [`Stemmer`] for the given language.
///
/// This is the public API for creating stemmers — `StemLanguage::to_algorithm` is
/// `pub(crate)` and not available outside `hyalo-core`.
pub fn create_stemmer(lang: StemLanguage) -> Stemmer {
    Stemmer::create(lang.to_algorithm())
}

// ---------------------------------------------------------------------------
// Corpus types
// ---------------------------------------------------------------------------

/// Input for building a corpus from pre-tokenized data (e.g. stored in the snapshot index).
pub struct PreTokenizedInput {
    /// Relative path that uniquely identifies the document.
    pub rel_path: String,
    /// Already-stemmed, field-aware tokens for this document.
    pub tokens: DocTokens,
}

/// Input data for a single document added to a [`Bm25InvertedIndex`].
#[derive(Debug, Clone, Default)]
pub struct DocumentInput {
    /// Relative path that uniquely identifies the document.
    pub rel_path: String,
    /// Title text (from frontmatter or the first H1 heading).
    pub title: String,
    /// Body text of the document (frontmatter excluded).
    pub body: String,
    /// Stemming language to use for this document's content.
    pub language: StemLanguage,
    /// 0-based indices of `body` lines that are outline headings, sorted.
    pub heading_lines: Vec<usize>,
    /// Frontmatter tags followed by `aliases` (the BM25F tags field).
    pub tags: Vec<String>,
}

/// Authored title used by the ranked corpus: frontmatter string, then first H1.
/// A filename fallback is useful for display, but has never been part of the
/// persisted BM25 token stream. Share this rule so disk scores agree with it.
pub fn document_title<'a>(
    properties: &'a indexmap::IndexMap<String, serde_json::Value>,
    sections: &'a [crate::types::OutlineSection],
) -> &'a str {
    properties
        .get("title")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| {
            sections
                .iter()
                .find(|s| s.level == 1)
                .and_then(|s| s.heading.as_deref())
                .unwrap_or("")
        })
}

/// Tokenize a [`DocumentInput`] into a [`PreTokenizedInput`].
///
/// Applies the same pipeline `create-index` uses ([`tokenize_document_text`]
/// with the effective `[search] code_blocks`), so indexed and disk-read
/// documents can be mixed in one corpus.
pub fn tokenize_document(doc: DocumentInput) -> PreTokenizedInput {
    let stemmer = create_stemmer(doc.language);
    let tokens = tokenize_document_text(
        &doc.title,
        &doc.body,
        &doc.heading_lines,
        doc.tags.iter().map(String::as_str),
        &stemmer,
        search_settings().skip_code_blocks,
    );
    PreTokenizedInput {
        rel_path: doc.rel_path,
        tokens,
    }
}

/// A ranked search result returned by [`Bm25InvertedIndex::score`].
pub struct Bm25Match {
    /// Relative path of the matched document.
    pub rel_path: String,
    /// BM25 relevance score (higher is more relevant).
    pub score: f64,
}

// ---------------------------------------------------------------------------
// Query language (see `query.rs`, DEC-333)
// ---------------------------------------------------------------------------

mod query;
mod sections;
mod tokenizer;
#[cfg(test)]
use tokenizer::is_scriptio_continua;
#[cfg(test)]
mod v4_tests;

pub use tokenizer::{
    DEFAULT_PROXIMITY_BONUS, DocTokenBuilder, DocTokens, FieldWeights, SearchSettings,
    TOKENIZER_VERSION, heading_body_lines, search_settings, set_search_settings, tokenize,
    tokenize_document_text,
};

pub use query::{
    CompiledQuery, FieldDocument, FieldKind, FieldSource, FieldTerm, MAX_PHRASE_SLOP,
    MAX_PREFIX_EXPANSION, NoFields, QuerySyntaxError, QueryWarnings, TermCandidate, TermSuggestion,
    corrected_query,
};
pub use sections::{FileSections, SectionHit, SectionScorer, SectionSpan};

/// Positive leaves compiled once for ranked body snippets. Shares scoring's
/// compiled query, so operators, negation, phrases, prefixes, per-language
/// stem alternatives and CJK never drift.
pub struct SnippetQuery {
    matcher: query::SnippetMatcher,
}

/// Resolve a ranked-search live read using the vault's canonical boundary.
/// Return the checked destination so callers do not reopen the original symlink.
/// This is a pre-open check, not a guarantee against concurrent filesystem changes.
pub fn resolve_document_path(
    dir: &std::path::Path,
    rel_path: &str,
) -> anyhow::Result<std::path::PathBuf> {
    use anyhow::Context;
    let canonical_dir = crate::discovery::canonicalize_vault_dir(dir)?;
    let path = dunce::canonicalize(dir.join(rel_path))
        .with_context(|| format!("resolving ranked document {rel_path}"))?;
    if !path.starts_with(&canonical_dir) {
        return Err(crate::discovery::FileResolveError::OutsideVault {
            path: rel_path.to_owned(),
            resolved: Some(path.display().to_string()),
        }
        .into());
    }
    Ok(path)
}

impl SnippetQuery {
    /// Compile with the query-time stemming language (no document override).
    pub fn new(query: &str, language: StemLanguage) -> Self {
        Self::from_compiled(&CompiledQuery::new(query, language))
    }

    /// Build a snippet selector from the same compiled query used for scoring.
    pub fn from_compiled(query: &CompiledQuery) -> Self {
        Self {
            matcher: query::SnippetMatcher::from_compiled(query),
        }
    }

    /// Number of distinct positive query tokens on a qualifying line (zero
    /// when it does not qualify) and the extra positions of its smallest
    /// window over the required groups (DEC-338). Body stemming must use the
    /// same document language as the BM25 corpus.
    fn rank_line(&self, line: &str, stemmer: &Stemmer) -> (usize, u64) {
        let tokens = tokenize(line, stemmer);
        let coverage = self.matcher.coverage(&tokens);
        if coverage == 0 {
            return (0, u64::MAX);
        }
        (coverage, self.matcher.window(&tokens))
    }

    /// Stream one selected result's raw body and keep the best three lines.
    /// Call only after result filtering, sorting and limiting. Snapshot tokens
    /// have no original text or file-line offsets, so cannot supply snippets.
    pub fn snippets(
        &self,
        dir: &std::path::Path,
        rel_path: &str,
        language: StemLanguage,
        sections: &[crate::types::OutlineSection],
        scope: &[crate::heading::SectionRange],
    ) -> anyhow::Result<Vec<crate::types::ContentMatch>> {
        use crate::scanner::{
            FileVisitor, LineOutcome, MAX_BODY_LINE_BYTES, ScanAction, read_line_capped,
        };
        let mut visitor = SnippetVisitor {
            query: self,
            stemmer: create_stemmer(language),
            sections,
            scope,
            best: Vec::with_capacity(4),
            skip_code: search_settings().skip_code_blocks,
            fence: crate::scanner::FenceTracker::new(),
        };
        let path = resolve_document_path(dir, rel_path)?;
        let file = std::fs::File::open(path)?;
        if file.metadata()?.len() > crate::scanner::MAX_FILE_SIZE {
            return Ok(Vec::new());
        }
        let mut reader = std::io::BufReader::new(file);
        let framed = crate::frontmatter::read_frame_for_body(&mut reader, MAX_BODY_LINE_BYTES)?;
        if framed.bytes().is_empty() {
            return Ok(Vec::new());
        }
        let fm_lines = if framed.frame().frontmatter().is_some() {
            memchr::memchr_iter(b'\n', framed.bytes()).count()
                + usize::from(!framed.bytes().ends_with(b"\n"))
        } else {
            0
        };
        let mut line = fm_lines.max(1);
        if fm_lines == 0
            && framed.first_line_complete()
            && let Ok(first_line) = std::str::from_utf8(framed.bytes())
        {
            visitor.on_raw_body_line(first_line.trim_end_matches(['\r', '\n']), line);
        }
        let mut buf = String::new();
        loop {
            buf.clear();
            let (n, outcome) = read_line_capped(&mut reader, &mut buf, MAX_BODY_LINE_BYTES)?;
            if n == 0 {
                break;
            }
            line += 1;
            if outcome == LineOutcome::Complete
                && visitor.on_raw_body_line(buf.trim_end_matches(['\r', '\n']), line)
                    == ScanAction::Stop
            {
                break;
            }
        }
        Ok(visitor.best.into_iter().map(|(_, _, m)| m).collect())
    }
}

struct SnippetVisitor<'a> {
    query: &'a SnippetQuery,
    stemmer: Stemmer,
    sections: &'a [crate::types::OutlineSection],
    scope: &'a [crate::heading::SectionRange],
    best: Vec<(usize, u64, crate::types::ContentMatch)>,
    skip_code: bool,
    fence: crate::scanner::FenceTracker,
}

impl crate::scanner::FileVisitor for SnippetVisitor<'_> {
    fn on_raw_body_line(&mut self, raw: &str, line: usize) -> crate::scanner::ScanAction {
        use crate::scanner::ScanAction;
        // Fence state sees every line, in scope or not.
        let skipped = self.skip_code && self.fence.process_line(raw);
        if skipped || (!self.scope.is_empty() && !crate::heading::in_scope(self.scope, line)) {
            return ScanAction::Continue;
        }
        let (count, window) = self.query.rank_line(raw, &self.stemmer);
        if count == 0 {
            return ScanAction::Continue;
        }
        if self.best.len() == 3 {
            let worst = &self.best[2];
            if (std::cmp::Reverse(worst.0), worst.1) <= (std::cmp::Reverse(count), window) {
                return ScanAction::Continue;
            }
        }
        let section = self
            .sections
            .iter()
            .rev()
            .find(|s| s.line <= line && s.heading.is_some())
            .and_then(|s| {
                s.heading
                    .as_ref()
                    .map(|heading| format!("{} {heading}", "#".repeat(usize::from(s.level))))
            })
            .unwrap_or_default();
        self.best.push((
            count,
            window,
            crate::types::ContentMatch {
                line,
                section,
                text: raw.to_owned(),
            },
        ));
        self.best
            .sort_by_key(|(count, window, m)| (std::cmp::Reverse(*count), *window, m.line));
        self.best.truncate(3);
        // Nothing later can beat three lines carrying every distinct query
        // token with no gap between the required terms; equal rank loses on
        // document order. Particularly useful for common single-term searches
        // over long indexed documents.
        if self.best.len() == 3
            && self.best[2].0 == self.query.matcher.max_coverage()
            && self.best[2].1 == 0
        {
            ScanAction::Stop
        } else {
            ScanAction::Continue
        }
    }

    fn needs_frontmatter(&self) -> bool {
        false
    }
}

// ---------------------------------------------------------------------------
// BM25 inverted index
// ---------------------------------------------------------------------------

/// Aggregate expanded-token budget, including temporary reconstruction slots.
pub(crate) const MAX_EXPANDED_TOKEN_BYTES: usize = 256 * 1024 * 1024;

/// Per-document scratch for [`Bm25InvertedIndex::reconstruct_tokens_with_budget`].
#[derive(Default)]
struct Parts<'t> {
    stream: Vec<(u32, &'t str)>,
    tags: Vec<&'t str>,
}

/// One document's entry in a term's posting list.
///
/// `positions` are the term's offsets (0-based, ascending) in the document's
/// title+body stream and `term_freq == positions.len()`. BM25F (DEC-337)
/// splits that stream count into fields: `title_tf` and `heading_tf` of the
/// positions are title or heading-line occurrences, the rest are body.
/// `tag_tf` counts occurrences in tags and aliases, which have no position —
/// so a posting may have no positions at all when the term occurs only in a
/// tag. The field counts are omitted from the wire format when zero, so a
/// body-only posting costs exactly what it did in format v3.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub(crate) struct Posting {
    pub(crate) doc_id: u32,
    pub(crate) term_freq: u32,
    /// Token offsets (ascending) — used for phrase checks and proximity.
    pub(crate) positions: Vec<u32>,
    #[serde(default, skip_serializing_if = "is_zero_u32")]
    pub(crate) title_tf: u32,
    #[serde(default, skip_serializing_if = "is_zero_u32")]
    pub(crate) heading_tf: u32,
    #[serde(default, skip_serializing_if = "is_zero_u32")]
    pub(crate) tag_tf: u32,
}

impl Posting {
    /// BM25F weighted term frequency: `Σ weight_f × tf_f`.
    pub(crate) fn weighted_tf(&self, weights: &FieldWeights) -> f64 {
        let body = self
            .term_freq
            .saturating_sub(self.title_tf)
            .saturating_sub(self.heading_tf);
        weights.title * f64::from(self.title_tf)
            + weights.headings * f64::from(self.heading_tf)
            + weights.tags * f64::from(self.tag_tf)
            + weights.body * f64::from(body)
    }
}

#[allow(clippy::trivially_copy_pass_by_ref)] // serde requires the by-ref shape
fn is_zero_u32(n: &u32) -> bool {
    *n == 0
}

/// Per-document field layout kept beside the postings so a document's
/// [`DocTokens`] can be reconstructed exactly (incremental updates, mixed
/// corpora) without storing the forward index twice.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DocMarks {
    #[serde(default, skip_serializing_if = "is_zero_u32")]
    title_len: u32,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    heading_runs: Vec<(u32, u32)>,
    #[serde(default, skip_serializing_if = "is_zero_u32")]
    tag_len: u32,
}

/// Serializable BM25 inverted index built from a collection of documents.
///
/// Build once with [`Bm25InvertedIndex::build`] or [`Bm25InvertedIndex::build_from_tokens`],
/// then call [`Bm25InvertedIndex::score`] as many times as needed. Because this type is
/// `Serialize + Deserialize`, it can be persisted in the snapshot index and reused across
/// invocations — avoiding the O(N·doc) corpus rebuild on every query.
/// [`Bm25InvertedIndex::apply_updates`] replaces documents in place (DEC-339).
///
/// ## BM25F scoring formula (DEC-337)
///
/// ```text
/// tf_w(t,d)   = Σ_f weight_f × tf_f(t,d)        f ∈ {title, headings, tags, body}
/// score(q, d) = Σ IDF(t) × (tf_w × (k1 + 1)) / (tf_w + k1 × (1 - b + b × |d|/avgdl))
///
/// where:
///   |d|    = all title, body and tag tokens of d (one combined length)
///   IDF(t) = ln(1 + (N - n(t) + 0.5) / (n(t) + 0.5))
///   k1 = 1.2, b = 0.75
/// ```
///
/// ## Query syntax
///
/// | Pattern | Semantics |
/// |---------|-----------|
/// | `foo bar` | AND — both terms required |
/// | `foo OR bar` | OR — either term sufficient |
/// | `a b OR c` | `OR` binds tighter than AND: a AND (b OR c) (DEC-333) |
/// | `(a OR b) -c` | Parentheses group; `-` negates a term, phrase or group |
/// | `"foo bar"` | Phrase — tokens must be adjacent and in order |
/// | `"foo bar"~3` | Phrase with slop — in order, up to 3 extra positions (DEC-338) |
/// | `conf*` | Prefix — any dictionary stem starting with `conf` |
/// | `title:x` `heading:x` `tag:x` `path:x` | Field predicates from index metadata |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Bm25InvertedIndex {
    /// Term → postings, sorted by doc_id.
    postings: HashMap<String, Vec<Posting>>,
    /// Number of title+body stream tokens in each document (indexed by doc_id).
    doc_lengths: Vec<u32>,
    /// doc_id → relative path mapping.
    doc_paths: Vec<String>,
    /// Field layout per document, parallel to `doc_lengths`.
    #[serde(default)]
    doc_marks: Vec<DocMarks>,
    /// Average BM25 document length (stream plus tag tokens).
    avgdl: f64,
    /// [`TOKENIZER_VERSION`] that produced every token in `postings`. `#[serde(default)]`
    /// makes a snapshot written before this field existed deserialize as `0`, which never
    /// equals the current [`TOKENIZER_VERSION`] — callers must treat that as "rebuild
    /// before trusting" (DEC-094 / F-2).
    #[serde(default)]
    tokenizer_version: u32,
    /// Whether fenced code blocks were excluded (`[search] code_blocks = "skip"`).
    /// A reader whose setting differs must not trust these postings.
    #[serde(default)]
    skip_code_blocks: bool,
}

impl Bm25InvertedIndex {
    // BM25 tuning constants
    const K1: f64 = 1.2;
    const B: f64 = 0.75;

    /// Builds a BM25 index from `docs`.
    ///
    /// Each document is tokenized with its own [`StemLanguage`]. No stemmer is
    /// stored in the index — pass a [`Stemmer`] to [`score`](Self::score) at query time.
    pub fn build(docs: Vec<DocumentInput>) -> Self {
        let pre_tokenized: Vec<PreTokenizedInput> =
            docs.into_iter().map(tokenize_document).collect();
        Self::build_from_tokens(pre_tokenized)
    }

    /// An index with no documents, stamped with the current tokenizer.
    fn empty() -> Self {
        Self {
            postings: HashMap::new(),
            doc_lengths: Vec::new(),
            doc_paths: Vec::new(),
            doc_marks: Vec::new(),
            avgdl: 256.0,
            tokenizer_version: TOKENIZER_VERSION,
            skip_code_blocks: search_settings().skip_code_blocks,
        }
    }

    /// Builds a BM25 index from pre-tokenized documents (e.g. stored in the snapshot index).
    ///
    /// Each document's tokens are already stemmed — no further tokenization is applied.
    pub fn build_from_tokens(docs: Vec<PreTokenizedInput>) -> Self {
        let mut index = Self::empty();
        index.doc_lengths.reserve(docs.len());
        index.doc_paths.reserve(docs.len());
        index.doc_marks.reserve(docs.len());
        for doc in docs {
            index.push_doc(doc.rel_path, &doc.tokens);
        }
        index.recompute_avgdl();
        index
    }

    /// Append one document with the next doc id.
    fn push_doc(&mut self, rel_path: String, doc: &DocTokens) {
        #[allow(clippy::cast_possible_truncation)]
        let doc_id = self.doc_paths.len() as u32;
        let mut tf: HashMap<&str, Posting> = HashMap::new();
        let mut runs = doc.heading_runs.iter().peekable();
        for (pos, token) in doc.tokens.iter().enumerate() {
            #[allow(clippy::cast_possible_truncation)]
            let pos = pos as u32;
            let entry = tf.entry(token.as_str()).or_default();
            entry.term_freq += 1;
            entry.positions.push(pos);
            if pos < doc.title_len {
                entry.title_tf += 1;
            } else {
                while runs.peek().is_some_and(|run| run.1 <= pos) {
                    runs.next();
                }
                if runs.peek().is_some_and(|run| run.0 <= pos) {
                    entry.heading_tf += 1;
                }
            }
        }
        for token in &doc.tag_tokens {
            tf.entry(token.as_str()).or_default().tag_tf += 1;
        }
        for (term, mut posting) in tf {
            posting.doc_id = doc_id;
            self.postings
                .entry(term.to_owned())
                .or_default()
                .push(posting);
        }
        #[allow(clippy::cast_possible_truncation)]
        self.doc_lengths.push(doc.tokens.len() as u32);
        #[allow(clippy::cast_possible_truncation)]
        self.doc_marks.push(DocMarks {
            title_len: doc.title_len,
            heading_runs: doc.heading_runs.clone(),
            tag_len: doc.tag_tokens.len() as u32,
        });
        self.doc_paths.push(rel_path);
    }

    /// BM25 length of `doc_id`: stream tokens plus tag tokens.
    fn bm25_len(&self, doc_id: usize) -> u64 {
        u64::from(self.doc_lengths[doc_id])
            + self
                .doc_marks
                .get(doc_id)
                .map_or(0, |m| u64::from(m.tag_len))
    }

    fn total_length(&self) -> Option<u64> {
        (0..self.doc_lengths.len()).try_fold(0_u64, |total, id| {
            let tags = self.doc_marks.get(id).map_or(0, |m| u64::from(m.tag_len));
            total
                .checked_add(u64::from(self.doc_lengths[id]))?
                .checked_add(tags)
        })
    }

    fn recompute_avgdl(&mut self) {
        let n = self.doc_paths.len();
        #[allow(clippy::cast_precision_loss)]
        let avgdl = if n == 0 {
            256.0
        } else {
            self.total_length().unwrap_or(u64::MAX) as f64 / n as f64
        };
        self.avgdl = avgdl;
    }

    /// Replace documents in place (DEC-339): every document whose path is in
    /// `remove`, or which `add` supplies again, loses its postings; then each
    /// `add` document is appended. Doc ids are compacted, so the result
    /// scores every query exactly like [`Self::build_from_tokens`] over the
    /// same documents — only the internal id order differs.
    ///
    /// One pass over the posting lists, however many documents change:
    /// cheaper than re-tokenizing the corpus by orders of magnitude.
    pub fn apply_updates(&mut self, remove: &HashSet<&str>, add: Vec<PreTokenizedInput>) {
        let replaced: HashSet<&str> = add.iter().map(|d| d.rel_path.as_str()).collect();
        let mut map: Vec<Option<u32>> = Vec::with_capacity(self.doc_paths.len());
        let mut next = 0u32;
        for path in &self.doc_paths {
            if remove.contains(path.as_str()) || replaced.contains(path.as_str()) {
                map.push(None);
            } else {
                map.push(Some(next));
                next += 1;
            }
        }
        if (next as usize) < self.doc_paths.len() {
            self.postings.retain(|_, posts| {
                posts.retain_mut(|p| match map.get(p.doc_id as usize).copied().flatten() {
                    Some(id) => {
                        p.doc_id = id;
                        true
                    }
                    None => false,
                });
                !posts.is_empty()
            });
            let keep = |i: &usize| map[*i].is_some();
            let mut i = 0usize;
            self.doc_paths.retain(|_| {
                let k = keep(&i);
                i += 1;
                k
            });
            i = 0;
            self.doc_lengths.retain(|_| {
                let k = keep(&i);
                i += 1;
                k
            });
            i = 0;
            self.doc_marks.retain(|_| {
                let k = keep(&i);
                i += 1;
                k
            });
        }
        drop(replaced);
        for doc in add {
            self.push_doc(doc.rel_path, &doc.tokens);
        }
        self.recompute_avgdl();
    }

    /// Build a `Bm25InvertedIndex` from `IndexEntry` values stored in a snapshot.
    ///
    /// Returns `None` if no entries have `bm25_tokens` set (i.e. the index was built
    /// without `bm25_tokenize = true`).
    pub fn build_from_entries(entries: &[crate::index::IndexEntry]) -> Option<Self> {
        let docs: Vec<PreTokenizedInput> = entries
            .iter()
            .filter_map(|e| {
                e.bm25_tokens.as_ref().map(|tokens| PreTokenizedInput {
                    rel_path: e.rel_path.clone(),
                    tokens: tokens.clone(),
                })
            })
            .collect();

        if docs.is_empty() {
            return None;
        }
        Some(Self::build_from_tokens(docs))
    }

    /// Return the total number of posting entries plus positions across all terms.
    ///
    /// Used as a defence-in-depth check during snapshot deserialization: a
    /// crafted index could claim a plausible number of *terms* while hiding an
    /// enormous number of per-term postings or per-posting positions arrays,
    /// causing large allocations.  Counting both prevents that attack.
    pub(crate) fn total_postings(&self) -> usize {
        self.postings
            .values()
            .flat_map(|posts| posts.iter())
            .fold(0_usize, |total, p| {
                total.saturating_add(1).saturating_add(p.positions.len())
            })
    }

    /// Full reconstruction admission, distinct from compact-postings scoring.
    #[cfg(test)]
    pub(crate) fn expansion_within_budget(&self, budget: usize) -> bool {
        self.selected_expansion_within_budget(&|_| true, budget)
    }

    fn selected_expansion_within_budget(
        &self,
        include: &impl Fn(&str) -> bool,
        budget: usize,
    ) -> bool {
        let selected = self.doc_paths.iter().filter(|path| include(path)).count();
        let Some(base) = selected
            .checked_mul(
                std::mem::size_of::<(u32, &str)>() + 2 * std::mem::size_of::<Vec<String>>() + 64,
            )
            .filter(|base| *base <= budget)
        else {
            return false;
        };
        self.postings
            .iter()
            .try_fold(base, |total, (term, posts)| {
                let width = term
                    .len()
                    .checked_add(std::mem::size_of::<String>())?
                    .checked_add(std::mem::size_of::<(u32, &str)>())?;
                posts.iter().try_fold(total, |sum, posting| {
                    let path = self.doc_paths.get(posting.doc_id as usize)?;
                    if !include(path) {
                        return Some(sum);
                    }
                    let occurrences = posting
                        .positions
                        .len()
                        .checked_add(posting.tag_tf as usize)?;
                    let next = sum.checked_add(width.checked_mul(occurrences)?)?;
                    (next <= budget).then_some(next)
                })
            })
            .is_some()
    }

    /// Returns **all** matches for `query`, ranked by BM25 score (highest first).
    ///
    /// Returns an empty vec when `query` produces no positive tokens or has no matches.
    /// A malformed query (unbalanced parenthesis, bare `*`) matches nothing;
    /// use [`CompiledQuery::parse`] to surface the error.
    pub fn score(&self, query: &str, stemmer: &Stemmer) -> Vec<Bm25Match> {
        self.score_compiled(&CompiledQuery::lenient_with_stemmer(query, stemmer))
    }

    /// Score an already-compiled query. Field terms other than `path:` match
    /// nothing here; use [`Bm25InvertedIndex::score_with_fields`] for those.
    pub fn score_compiled(&self, query: &CompiledQuery) -> Vec<Bm25Match> {
        self.score_with_fields(query, &NoFields)
    }

    /// Reconstruct every document's [`DocTokens`] from postings.
    ///
    /// The snapshot format strips per-entry `bm25_tokens` when a persisted
    /// inverted index is present (roughly halves snapshot size), so a loaded
    /// snapshot's entries carry no tokens. Postings store, per (term, doc),
    /// the position of every stream occurrence and the tag count, and
    /// `doc_marks` the field layout — exactly enough to invert back to the
    /// original record (tag tokens come back sorted, as they were built).
    ///
    /// One pass over all postings: O(total postings), no per-document scans.
    pub fn reconstruct_all_tokens(&self) -> anyhow::Result<HashMap<&str, DocTokens>> {
        self.reconstruct_tokens_where(|_| true)
    }

    /// Recover only selected documents, preserving token order and duplicates.
    /// Empty selections return without traversing postings. Nonempty selections
    /// use one posting traversal and allocate token storage only for selected docs.
    pub fn reconstruct_selected_tokens(
        &self,
        selected: &HashSet<&str>,
    ) -> anyhow::Result<HashMap<&str, DocTokens>> {
        if selected.is_empty() {
            return Ok(HashMap::new());
        }
        self.reconstruct_tokens_where(|path| selected.contains(path))
    }

    fn reconstruct_tokens_where(
        &self,
        include: impl Fn(&str) -> bool,
    ) -> anyhow::Result<HashMap<&str, DocTokens>> {
        self.reconstruct_tokens_with_budget(include, MAX_EXPANDED_TOKEN_BYTES)
    }

    fn reconstruct_tokens_with_budget(
        &self,
        include: impl Fn(&str) -> bool,
        budget: usize,
    ) -> anyhow::Result<HashMap<&str, DocTokens>> {
        anyhow::ensure!(
            self.selected_expansion_within_budget(&include, budget),
            "BM25 token reconstruction exceeds the {budget}-byte allocation budget; compact indexed scoring remains available"
        );
        let selected: Vec<_> = self
            .doc_paths
            .iter()
            .enumerate()
            .filter(|(_, path)| include(path))
            .map(|(id, path)| {
                #[allow(clippy::cast_possible_truncation)]
                (id as u32, path.as_str())
            })
            .collect();
        if selected.is_empty() {
            return Ok(HashMap::new());
        }
        let mut by_doc: HashMap<u32, Parts<'_>> = selected
            .iter()
            .map(|&(id, _)| (id, Parts::default()))
            .collect();
        for (term, posts) in &self.postings {
            for posting in posts {
                if let Some(parts) = by_doc.get_mut(&posting.doc_id) {
                    parts
                        .stream
                        .extend(posting.positions.iter().map(|&pos| (pos, term.as_str())));
                    parts
                        .tags
                        .extend(std::iter::repeat_n(term.as_str(), posting.tag_tf as usize));
                }
            }
        }
        let mut out = HashMap::with_capacity(selected.len());
        for (doc_id, path) in selected {
            let mut parts = by_doc.remove(&doc_id).unwrap_or_default();
            // Positions uniquely identify occurrences, restoring the token order
            // required for phrase matching while retaining repeated terms.
            parts.stream.sort_unstable_by_key(|&(pos, _)| pos);
            parts.tags.sort_unstable();
            let marks = self
                .doc_marks
                .get(doc_id as usize)
                .cloned()
                .unwrap_or_default();
            out.insert(
                path,
                DocTokens {
                    tokens: parts
                        .stream
                        .into_iter()
                        .map(|(_, term)| term.to_owned())
                        .collect(),
                    title_len: marks.title_len,
                    heading_runs: marks.heading_runs,
                    tag_tokens: parts.tags.into_iter().map(str::to_owned).collect(),
                },
            );
        }
        Ok(out)
    }

    /// Paths of the documents that contribute to this corpus's statistics.
    pub fn document_paths(&self) -> impl Iterator<Item = &str> {
        self.doc_paths.iter().map(String::as_str)
    }

    /// Returns the total number of documents in the index.
    pub fn doc_count(&self) -> usize {
        self.doc_paths.len()
    }

    /// Returns the [`TOKENIZER_VERSION`] that produced this index's tokens.
    ///
    /// Callers holding a persisted index (loaded from a snapshot) must compare
    /// this against the current [`TOKENIZER_VERSION`] before trusting it for
    /// scoring — see the field doc comment and DEC-094 (F-2).
    #[must_use]
    pub fn tokenizer_version(&self) -> u32 {
        self.tokenizer_version
    }

    /// Whether fenced code blocks were excluded when these postings were built.
    #[must_use]
    pub fn skip_code_blocks(&self) -> bool {
        self.skip_code_blocks
    }

    /// `true` when this index was built by the current tokenizer with the
    /// effective `[search] code_blocks` setting — the precondition for
    /// serving queries from it, or updating it incrementally.
    #[must_use]
    pub fn is_current(&self) -> bool {
        self.tokenizer_version == TOKENIZER_VERSION
            && self.skip_code_blocks == search_settings().skip_code_blocks
    }

    /// Validate compact scoring structure: unique documents, coherent finite
    /// length metadata, and strictly ordered, bounded postings, positions and
    /// per-field term frequencies.
    ///
    /// A crafted snapshot could contain `doc_id` values that exceed the length of
    /// `doc_paths` or `doc_lengths`, causing an out-of-bounds panic in [`score`](Self::score).
    /// This method must be called after deserialization before the index is used.
    ///
    /// Returns `true` if the index is structurally consistent, `false` otherwise.
    pub(crate) fn validate_doc_ids(&self) -> bool {
        let max_id = self.doc_paths.len();
        if self.doc_lengths.len() != max_id || self.doc_marks.len() != max_id {
            return false;
        }
        if !self.avgdl.is_finite()
            || self.avgdl < 0.0
            || self.doc_paths.iter().collect::<HashSet<_>>().len() != max_id
        {
            return false;
        }
        let marks_ok = self
            .doc_marks
            .iter()
            .zip(&self.doc_lengths)
            .all(|(m, &len)| {
                m.title_len <= len
                    && m.heading_runs
                        .iter()
                        .all(|&(start, end)| start >= m.title_len && start < end && end <= len)
                    && m.heading_runs.windows(2).all(|pair| pair[0].1 <= pair[1].0)
            });
        if !marks_ok {
            return false;
        }
        if max_id > 0 {
            let Some(total) = self.total_length() else {
                return false;
            };
            #[allow(clippy::cast_precision_loss)]
            let expected = total as f64 / max_id as f64;
            if (self.avgdl - expected).abs() > f64::EPSILON * expected.max(1.0) * 4.0 {
                return false;
            }
        }
        self.postings.values().all(|posts| {
            !posts.is_empty()
                && posts.windows(2).all(|pair| pair[0].doc_id < pair[1].doc_id)
                && posts.iter().all(|p| {
                    let Some(length) = self.doc_lengths.get(p.doc_id as usize) else {
                        return false;
                    };
                    let tag_len = self.doc_marks[p.doc_id as usize].tag_len;
                    (!p.positions.is_empty() || p.tag_tf > 0)
                        && p.term_freq as usize == p.positions.len()
                        && p.title_tf
                            .checked_add(p.heading_tf)
                            .is_some_and(|f| f <= p.term_freq)
                        && p.tag_tf <= tag_len
                        && p.positions.iter().all(|position| position < length)
                        && p.positions.windows(2).all(|pair| pair[0] < pair[1])
                })
        })
    }

    // ------------------------------------------------------------------
    // Test helpers
    // ------------------------------------------------------------------

    /// Constructs a `Bm25InvertedIndex` with explicit field values for use in tests.
    ///
    /// This exists so tests can create structurally invalid indices (e.g. a posting
    /// with a `doc_id` that exceeds `doc_paths.len()`) without going through the
    /// safe `build` / `build_from_tokens` constructors.
    #[cfg(test)]
    pub(crate) fn new_for_test(
        postings: HashMap<String, Vec<Posting>>,
        doc_lengths: Vec<u32>,
        doc_paths: Vec<String>,
        avgdl: f64,
    ) -> Self {
        let doc_marks = vec![DocMarks::default(); doc_lengths.len()];
        Self {
            postings,
            doc_lengths,
            doc_paths,
            doc_marks,
            avgdl,
            tokenizer_version: TOKENIZER_VERSION,
            skip_code_blocks: false,
        }
    }

    /// Overrides `tokenizer_version` on a test-built index, to simulate a
    /// snapshot persisted by an older `tokenize()` algorithm.
    #[cfg(test)]
    pub(crate) fn with_tokenizer_version_for_test(mut self, version: u32) -> Self {
        self.tokenizer_version = version;
        self
    }

    // ------------------------------------------------------------------
    // Private helpers
    // ------------------------------------------------------------------

    /// Returns the set of `doc_id`s that contain **all** given terms in the
    /// positional stream.
    fn docs_with_all_terms(&self, terms: &[String]) -> HashSet<u32> {
        if terms.iter().any(|t| !self.postings.contains_key(t)) {
            return HashSet::new();
        }
        let positional = |postings: &Vec<Posting>| {
            postings
                .iter()
                .filter(|p| !p.positions.is_empty())
                .map(|p| p.doc_id)
                .collect::<HashSet<u32>>()
        };
        let mut iter = terms.iter().filter_map(|t| self.postings.get(t));
        let first = match iter.next() {
            Some(postings) => positional(postings),
            None => return HashSet::new(),
        };
        iter.fold(first, |acc, postings| {
            let ids = positional(postings);
            acc.intersection(&ids).copied().collect()
        })
    }

    /// Positions of `term` in `doc_id` (empty when absent).
    pub(crate) fn positions_of(&self, term: &str, doc_id: u32) -> &[u32] {
        self.postings
            .get(term)
            .and_then(|ps| {
                ps.binary_search_by_key(&doc_id, |p| p.doc_id)
                    .ok()
                    .map(|idx| ps[idx].positions.as_slice())
            })
            .unwrap_or(&[] as &[u32])
    }

    /// Returns `true` if `terms` appear in order in `doc_id` with at most
    /// `slop` extra positions between the first and the last (0 = adjacent).
    fn has_phrase_at_positions(&self, terms: &[String], doc_id: u32, slop: u32) -> bool {
        if terms.is_empty() {
            return false;
        }
        let positions: Vec<&[u32]> = terms.iter().map(|t| self.positions_of(t, doc_id)).collect();
        query::phrase_in_positions(&positions, slop)
    }
}

/// Returns `true` if every token in `query` is a boolean operator keyword (`and`, `or`)
/// and no searchable terms remain after parsing.
///
/// Use this to detect queries like `"and"` or `"or"` that are silently consumed as
/// operators, leaving an empty query that matches nothing.
pub fn query_is_operator_only(query: &str) -> bool {
    query::operator_only(query)
}

/// Returns `true` if the BM25 results suggest the query has low discriminative power
/// (e.g. all terms are very common stop-words). Heuristic: more than 80% of documents
/// matched and the top score is below 1.0.
pub fn is_low_discriminative(matches: &[Bm25Match], total_docs: usize) -> bool {
    if total_docs == 0 || matches.is_empty() {
        return false;
    }
    debug_assert!(
        matches.len() <= total_docs,
        "matches ({}) exceeds total_docs ({})",
        matches.len(),
        total_docs
    );
    #[allow(clippy::cast_precision_loss)]
    let match_ratio = matches.len() as f64 / total_docs as f64;
    let max_score = matches.iter().map(|m| m.score).fold(0.0_f64, f64::max);
    match_ratio > 0.8 && max_score < 1.0
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn malformed_phrase_offsets_never_wrap_even_before_admission() {
        let forged = Bm25InvertedIndex::new_for_test(
            HashMap::from([
                (
                    "foo".into(),
                    vec![Posting {
                        doc_id: 0,
                        term_freq: 1,
                        positions: vec![u32::MAX],
                        ..Default::default()
                    }],
                ),
                (
                    "bar".into(),
                    vec![Posting {
                        doc_id: 0,
                        term_freq: 1,
                        positions: vec![0],
                        ..Default::default()
                    }],
                ),
            ]),
            vec![2],
            vec!["doc.md".into()],
            2.0,
        );
        assert!(!forged.validate_doc_ids());
        let stemmer = Stemmer::create(rust_stemmers::Algorithm::English);
        assert!(forged.score("\"foo bar\"", &stemmer).is_empty());
    }

    /// BUG-4 (iter-244): token lists reconstructed from postings must be
    /// identical to the tokens that built the index — snapshot entries have
    /// their `bm25_tokens` stripped at write time, so a post-mutation rebuild
    /// inverts the postings back into tokens for every untouched entry.
    #[test]
    fn reconstruct_all_tokens_round_trips_build_inputs() {
        let docs = vec![
            PreTokenizedInput {
                rel_path: "a.md".to_owned(),
                tokens: vec!["alpha".to_owned(), "beta".to_owned(), "alpha".to_owned()].into(),
            },
            PreTokenizedInput {
                rel_path: "b.md".to_owned(),
                tokens: vec!["beta".to_owned()].into(),
            },
            PreTokenizedInput {
                rel_path: "empty.md".to_owned(),
                tokens: vec![].into(),
            },
        ];
        let index = Bm25InvertedIndex::build_from_tokens(docs);
        let reconstructed = index.reconstruct_all_tokens().unwrap();
        assert_eq!(reconstructed.len(), 3);
        assert_eq!(
            reconstructed.get("a.md").unwrap().tokens,
            vec!["alpha".to_owned(), "beta".to_owned(), "alpha".to_owned()]
        );
        assert_eq!(
            reconstructed.get("b.md").unwrap().tokens,
            vec!["beta".to_owned()]
        );
        assert_eq!(
            reconstructed.get("empty.md").unwrap().tokens,
            Vec::<String>::new()
        );
    }

    #[test]
    fn selected_token_reconstruction_preserves_subset_empty_docs_and_unknown_paths() {
        let index = Bm25InvertedIndex::build_from_tokens(vec![
            PreTokenizedInput {
                rel_path: "selected.md".into(),
                tokens: vec!["beta".into(), "alpha".into(), "beta".into()].into(),
            },
            PreTokenizedInput {
                rel_path: "excluded.md".into(),
                tokens: vec!["unrelated".into(); 1000].into(),
            },
            PreTokenizedInput {
                rel_path: "empty.md".into(),
                tokens: vec![].into(),
            },
        ]);
        let selected = HashSet::from(["selected.md", "empty.md", "missing.md"]);
        let recovered = index.reconstruct_selected_tokens(&selected).unwrap();
        assert_eq!(recovered.len(), 2);
        assert_eq!(recovered["selected.md"].tokens, ["beta", "alpha", "beta"]);
        assert!(
            recovered["empty.md"].tokens.is_empty(),
            "expected empty, got {:?}",
            recovered["empty.md"]
        );
        assert!(!recovered.contains_key("excluded.md"));
        assert!(!recovered.contains_key("missing.md"));
        assert!(
            index
                .reconstruct_selected_tokens(&HashSet::new())
                .unwrap()
                .is_empty()
        );
        assert!(
            index
                .reconstruct_selected_tokens(&HashSet::from(["missing.md"]))
                .unwrap()
                .is_empty()
        );
        let all = index.reconstruct_all_tokens().unwrap();
        for path in ["selected.md", "empty.md"] {
            assert_eq!(recovered[path], all[path]);
        }
    }

    /// Scores must be identical between an index built from the original
    /// token lists and one rebuilt from postings-reconstructed tokens.
    #[test]
    fn scores_unchanged_after_postings_reconstruction() {
        let docs = vec![
            PreTokenizedInput {
                rel_path: "a.md".to_owned(),
                tokens: vec!["rust".to_owned(), "memory".to_owned(), "rust".to_owned()].into(),
            },
            PreTokenizedInput {
                rel_path: "b.md".to_owned(),
                tokens: vec!["rust".to_owned(), "rust".to_owned(), "rust".to_owned()].into(),
            },
            PreTokenizedInput {
                rel_path: "c.md".to_owned(),
                tokens: vec!["memory".to_owned()].into(),
            },
        ];
        let original = Bm25InvertedIndex::build_from_tokens(docs);
        let reconstructed_tokens = original.reconstruct_all_tokens().unwrap();
        let rebuilt_docs: Vec<PreTokenizedInput> = ["a.md", "b.md", "c.md"]
            .into_iter()
            .map(|p| PreTokenizedInput {
                rel_path: p.to_owned(),
                tokens: reconstructed_tokens.get(p).unwrap().clone(),
            })
            .collect();
        let rebuilt = Bm25InvertedIndex::build_from_tokens(rebuilt_docs);

        let stemmer = make_stemmer(StemLanguage::English);
        let s1 = original.score("rust OR memory", &stemmer);
        let s2 = rebuilt.score("rust OR memory", &stemmer);
        let to_pairs = |v: Vec<Bm25Match>| {
            v.into_iter()
                .map(|m| (m.rel_path, m.score))
                .collect::<Vec<_>>()
        };
        assert_eq!(
            to_pairs(s1),
            to_pairs(s2),
            "scores must be identical after reconstruction"
        );
    }

    fn make_stemmer(lang: StemLanguage) -> Stemmer {
        Stemmer::create(lang.to_algorithm())
    }

    // ------------------------------------------------------------------
    // tokenize
    // ------------------------------------------------------------------

    #[test]
    fn test_tokenize_english() {
        let stemmer = make_stemmer(StemLanguage::English);
        let tokens = tokenize("running quickly", &stemmer);
        assert_eq!(tokens, vec!["run", "quick"]);
    }

    #[test]
    fn test_tokenize_french() {
        let stemmer = make_stemmer(StemLanguage::French);
        let tokens = tokenize("mangeons rapidement", &stemmer);
        // Just verify we get two non-empty tokens; exact stems depend on the snowball algorithm.
        assert_eq!(tokens.len(), 2);
        assert!(tokens.iter().all(|t| !t.is_empty()));
    }

    #[test]
    fn test_tokenize_cjk_run_becomes_bigrams() {
        let stemmer = make_stemmer(StemLanguage::English);
        // "日本語" (Japanese, no inter-word spaces) must not collapse into one
        // unmatchable token (F-2) — it should become overlapping bigrams.
        let tokens = tokenize("日本語", &stemmer);
        assert_eq!(tokens, vec!["日本", "本語"]);
    }

    #[test]
    fn test_tokenize_cjk_single_char_run() {
        let stemmer = make_stemmer(StemLanguage::English);
        // A lone CJK character has no bigram partner — kept as a unigram.
        let tokens = tokenize("語", &stemmer);
        assert_eq!(tokens, vec!["語"]);
    }

    #[test]
    fn test_tokenize_cjk_query_matches_substring_of_longer_run() {
        // A query for a CJK substring should tokenize to a subset of the bigrams
        // produced for the longer run it appears in — the mechanism that lets a
        // BM25 AND query over the bigrams actually match (F-2 acceptance criterion).
        let stemmer = make_stemmer(StemLanguage::English);
        let doc_tokens = tokenize("日本語のテキストです", &stemmer);
        let query_tokens = tokenize("日本語", &stemmer);
        assert!(
            query_tokens.iter().all(|t| doc_tokens.contains(t)),
            "query bigrams {query_tokens:?} should all appear in document bigrams {doc_tokens:?}"
        );
    }

    #[test]
    fn test_tokenize_mixed_cjk_and_ascii_words_both_present() {
        let stemmer = make_stemmer(StemLanguage::English);
        // Space-separated CJK and ASCII words tokenize independently: the ASCII
        // word keeps the normal stem pipeline, the CJK run becomes bigrams.
        let tokens = tokenize("hello 日本語", &stemmer);
        assert!(tokens.contains(&"hello".to_owned()));
        assert!(tokens.contains(&"日本".to_owned()));
        assert!(tokens.contains(&"本語".to_owned()));
    }

    #[test]
    fn test_tokenize_no_separator_mixed_run_keeps_latin_word_searchable() {
        // Review round finding 1: a single alphanumeric run with NO separator
        // between CJK and Latin (common in real CJK technical writing, e.g.
        // "日本語Docker入門ガイドです") must not force the Latin substring into
        // character bigrams -- "Docker" must survive as one exact token, not
        // fragment into "語d"/"ck"/"er入".
        let stemmer = make_stemmer(StemLanguage::English);
        let tokens = tokenize("日本語Docker入門ガイドです", &stemmer);
        assert!(
            tokens.contains(&"docker".to_owned()),
            "Docker must survive as a whole token: {tokens:?}"
        );
        // No token may mix a scriptio-continua character with a non-scriptio-
        // continua character -- that mixing is exactly the old bug (a bigram
        // like "語D" straddling the script boundary).
        assert!(
            tokens.iter().all(|t| {
                let all_cjk = t.chars().all(is_scriptio_continua);
                let none_cjk = t.chars().all(|c| !is_scriptio_continua(c));
                all_cjk || none_cjk
            }),
            "no token may mix scriptio-continua and non-scriptio-continua characters: {tokens:?}"
        );
    }

    #[test]
    fn test_tokenize_no_separator_mixed_run_query_matches_both_substrings() {
        // The same document must be findable by a query for either the CJK
        // part or the Latin part -- the acceptance criterion behind finding 1.
        let stemmer = make_stemmer(StemLanguage::English);
        let doc_tokens = tokenize("日本語Docker入門ガイドです", &stemmer);

        let latin_query = tokenize("Docker", &stemmer);
        assert!(
            latin_query.iter().all(|t| doc_tokens.contains(t)),
            "query {latin_query:?} should be a subset of doc tokens {doc_tokens:?}"
        );

        let cjk_query = tokenize("日本語", &stemmer);
        assert!(
            cjk_query.iter().all(|t| doc_tokens.contains(t)),
            "query {cjk_query:?} should be a subset of doc tokens {doc_tokens:?}"
        );
    }

    #[test]
    fn test_tokenize_no_separator_cjk_and_latin_word_example() {
        // The review's brief example: "日本語test" with zero separator.
        let stemmer = make_stemmer(StemLanguage::English);
        let tokens = tokenize("日本語test", &stemmer);
        assert!(tokens.contains(&"test".to_owned()), "tokens: {tokens:?}");
        assert!(tokens.contains(&"日本".to_owned()), "tokens: {tokens:?}");
        assert!(tokens.contains(&"本語".to_owned()), "tokens: {tokens:?}");
    }

    #[test]
    fn test_tokenize_mixed_han_hiragana_stays_in_one_bigram_segment() {
        // Segmentation boundaries are drawn only between scriptio-continua and
        // non-scriptio-continua characters -- never between different CJK
        // sub-scripts. "日本語です" (Han "日本語" immediately followed by
        // Hiragana "です", the ordinary shape of a Japanese sentence) must
        // produce a bigram straddling the Han/Hiragana boundary ("語で"), not
        // stop the segment at the script change.
        let stemmer = make_stemmer(StemLanguage::English);
        let tokens = tokenize("日本語です", &stemmer);
        assert!(
            tokens.contains(&"語で".to_owned()),
            "a bigram must straddle the Han/Hiragana boundary: {tokens:?}"
        );
    }

    #[test]
    fn test_tokenize_ascii_fast_path_unaffected_by_cjk_handling() {
        // The is_ascii() fast path must produce byte-identical output to the
        // pre-F-2 behaviour for pure-ASCII text (no scan-perf regression).
        let stemmer = make_stemmer(StemLanguage::English);
        let tokens = tokenize("The Quick-Brown Fox_Jumps", &stemmer);
        // Tokenizer v4 (DEC-336): joined identifiers emit whole then parts.
        assert_eq!(
            tokens,
            vec![
                "the",
                "quickbrown",
                "quick",
                "brown",
                "foxjump",
                "fox",
                "jump"
            ]
        );
    }

    #[test]
    fn test_tokenize_splits_on_punctuation() {
        let stemmer = make_stemmer(StemLanguage::English);
        // "hello-world foo_bar" yields each identifier whole plus its parts
        // (DEC-336): helloworld, hello, world, foobar, foo, bar.
        let tokens = tokenize("hello-world foo_bar", &stemmer);
        assert_eq!(tokens.len(), 6);
    }

    #[test]
    fn test_tokenize_unicode_lowercase() {
        let stemmer = make_stemmer(StemLanguage::English);
        // "ÜBER" lowercases to "über"; the English stemmer leaves it as-is since it's not an
        // ASCII word, but the key assertion is that it is lowercased.
        let tokens = tokenize("ÜBER", &stemmer);
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0], tokens[0].to_lowercase());
    }

    #[test]
    fn test_tokenize_per_token_lowercase() {
        let stemmer = make_stemmer(StemLanguage::English);
        // Mixed-case words should be lowercased per-token, not as a single string.
        let tokens = tokenize("RUST Programming", &stemmer);
        assert_eq!(tokens.len(), 2);
        for t in &tokens {
            assert_eq!(t, &t.to_lowercase(), "token {t:?} should be lowercase");
        }
    }

    #[test]
    fn test_tokenize_document_function() {
        let input = DocumentInput {
            rel_path: "test.md".to_owned(),
            title: "Running guide".to_owned(),
            body: "A guide to running faster.".to_owned(),
            language: StemLanguage::English,
            ..Default::default()
        };
        let pre = tokenize_document(input);
        assert_eq!(pre.rel_path, "test.md");
        // "running" and "run" both stem to "run"
        assert!(pre.tokens.tokens.contains(&"run".to_owned()));
    }

    // ------------------------------------------------------------------
    // resolve_language / parse_language
    // ------------------------------------------------------------------

    #[test]
    fn test_resolve_language_precedence() {
        // frontmatter wins over cli and config
        assert_eq!(
            resolve_language(Some("french"), Some("german"), Some("spanish")),
            StemLanguage::French
        );
        // cli wins when frontmatter absent
        assert_eq!(
            resolve_language(None, Some("german"), Some("spanish")),
            StemLanguage::German
        );
        // config wins when frontmatter and cli absent
        assert_eq!(
            resolve_language(None, None, Some("spanish")),
            StemLanguage::Spanish
        );
        // falls back to English when all absent
        assert_eq!(resolve_language(None, None, None), StemLanguage::English);
        // invalid frontmatter value falls through to cli
        assert_eq!(
            resolve_language(Some("klingon"), Some("italian"), None),
            StemLanguage::Italian
        );
    }

    #[test]
    fn test_parse_language_valid() {
        let cases = [
            ("arabic", StemLanguage::Arabic),
            ("Danish", StemLanguage::Danish),
            ("DUTCH", StemLanguage::Dutch),
            ("English", StemLanguage::English),
            ("finnish", StemLanguage::Finnish),
            ("French", StemLanguage::French),
            ("german", StemLanguage::German),
            ("greek", StemLanguage::Greek),
            ("Hungarian", StemLanguage::Hungarian),
            ("Italian", StemLanguage::Italian),
            ("norwegian", StemLanguage::Norwegian),
            ("portuguese", StemLanguage::Portuguese),
            ("romanian", StemLanguage::Romanian),
            ("russian", StemLanguage::Russian),
            ("spanish", StemLanguage::Spanish),
            ("Swedish", StemLanguage::Swedish),
            ("Tamil", StemLanguage::Tamil),
            ("Turkish", StemLanguage::Turkish),
        ];
        for (input, expected) in cases {
            assert_eq!(parse_language(input).expect(input), expected, "{input}");
        }
    }

    #[test]
    fn test_parse_language_invalid() {
        assert!(parse_language("klingon").is_err());
        assert!(parse_language("").is_err());
        assert!(parse_language("xx").is_err());
    }

    #[test]
    fn test_parse_language_iso639_codes() {
        assert_eq!(parse_language("en").unwrap(), StemLanguage::English);
        assert_eq!(parse_language("de").unwrap(), StemLanguage::German);
        assert_eq!(parse_language("fr").unwrap(), StemLanguage::French);
        assert_eq!(parse_language("es").unwrap(), StemLanguage::Spanish);
        assert_eq!(parse_language("ar").unwrap(), StemLanguage::Arabic);
        assert_eq!(parse_language("no").unwrap(), StemLanguage::Norwegian);
        assert_eq!(parse_language("nb").unwrap(), StemLanguage::Norwegian);
        assert_eq!(parse_language("EN").unwrap(), StemLanguage::English);
    }

    // ------------------------------------------------------------------
    // Bm25InvertedIndex — basic corpus tests
    // ------------------------------------------------------------------

    fn doc(rel_path: &str, title: &str, body: &str) -> DocumentInput {
        DocumentInput {
            rel_path: rel_path.to_owned(),
            title: title.to_owned(),
            body: body.to_owned(),
            language: StemLanguage::English,
            ..Default::default()
        }
    }

    #[test]
    fn test_bm25_corpus_basic_search() {
        let docs = vec![
            doc(
                "rust.md",
                "Rust programming",
                "Rust is a systems programming language.",
            ),
            doc(
                "python.md",
                "Python programming",
                "Python is a scripting language.",
            ),
            doc(
                "cooking.md",
                "Cooking recipes",
                "How to bake a delicious cake.",
            ),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // With AND semantics, "rust programming" requires both terms.
        // rust.md has both; python.md has "programming" but not "rust".
        let results = index.score("rust programming", &stemmer);
        assert!(!results.is_empty(), "expected at least one result");
        // The Rust document should rank first (it has both terms in title + body).
        assert_eq!(results[0].rel_path, "rust.md");
    }

    #[test]
    fn test_bm25_corpus_stemming_matches() {
        // "run" should match a doc that contains "running" because stemming normalises both.
        let docs = vec![
            doc(
                "running.md",
                "Running guide",
                "I enjoy running every morning.",
            ),
            doc(
                "cooking.md",
                "Cooking guide",
                "I enjoy cooking every evening.",
            ),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("run", &stemmer);
        assert!(!results.is_empty(), "expected matches via stemming");
        assert_eq!(results[0].rel_path, "running.md");
    }

    #[test]
    fn test_bm25_corpus_relevance_ranking() {
        // The doc with more occurrences of the query term should rank higher.
        let docs = vec![
            doc(
                "many.md",
                "Rust tips",
                "Rust Rust Rust Rust Rust is great for systems programming.",
            ),
            doc(
                "few.md",
                "Languages",
                "Rust is one option among many languages.",
            ),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("rust", &stemmer);
        assert!(results.len() >= 2);
        assert_eq!(results[0].rel_path, "many.md");
    }

    #[test]
    fn test_bm25_corpus_empty_query() {
        let docs = vec![doc("a.md", "Title", "Some body text.")];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("", &stemmer);
        assert!(results.is_empty());
    }

    #[test]
    fn test_bm25_corpus_no_matches() {
        let docs = vec![doc("a.md", "Title", "Some body text.")];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("xyzzy42quux", &stemmer);
        assert!(results.is_empty());
    }

    #[test]
    fn test_bm25_corpus_single_doc() {
        let docs = vec![doc(
            "single.md",
            "Only document",
            "This is the only document.",
        )];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("document", &stemmer);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].rel_path, "single.md");
    }

    #[test]
    fn test_bm25_corpus_score_returns_all() {
        let docs = vec![
            doc("a.md", "Alpha", "The quick brown fox."),
            doc("b.md", "Beta", "The lazy dog slept."),
            doc("c.md", "Gamma", "No matching content here."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // "quick" matches only doc a, so score() should return exactly 1 result.
        let all = index.score("quick", &stemmer);
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].rel_path, "a.md");
    }

    // ------------------------------------------------------------------
    // AND scoring
    // ------------------------------------------------------------------

    #[test]
    fn test_bm25_and_scoring() {
        let docs = vec![
            doc("both.md", "Alpha beta", "This doc has alpha and beta."),
            doc("alpha_only.md", "Alpha", "This doc has only alpha."),
            doc("beta_only.md", "Beta", "This doc has only beta."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // AND query: only docs with BOTH terms should appear.
        let results = index.score("alpha beta", &stemmer);
        let paths: Vec<&str> = results.iter().map(|r| r.rel_path.as_str()).collect();
        assert!(
            paths.contains(&"both.md"),
            "both.md should match: {paths:?}"
        );
        assert!(
            !paths.contains(&"alpha_only.md"),
            "alpha_only.md should be excluded: {paths:?}"
        );
        assert!(
            !paths.contains(&"beta_only.md"),
            "beta_only.md should be excluded: {paths:?}"
        );
    }

    // ------------------------------------------------------------------
    // OR scoring
    // ------------------------------------------------------------------

    #[test]
    fn test_bm25_or_scoring() {
        let docs = vec![
            doc("rust.md", "Rust", "Rust systems programming."),
            doc("python.md", "Python", "Python scripting language."),
            doc("cooking.md", "Cooking", "Recipes and ingredients."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // OR query: docs with either rust OR python should appear, cooking should not.
        let results = index.score("rust OR python", &stemmer);
        let paths: Vec<&str> = results.iter().map(|r| r.rel_path.as_str()).collect();
        assert!(
            paths.contains(&"rust.md"),
            "rust.md should match: {paths:?}"
        );
        assert!(
            paths.contains(&"python.md"),
            "python.md should match: {paths:?}"
        );
        assert!(
            !paths.contains(&"cooking.md"),
            "cooking.md should not match: {paths:?}"
        );
    }

    // ------------------------------------------------------------------
    // Phrase matching
    // ------------------------------------------------------------------

    #[test]
    fn test_bm25_phrase_matching() {
        let docs = vec![
            doc(
                "consecutive.md",
                "Fast Rust",
                "Rust is a fast systems language.",
            ),
            doc(
                "non_consecutive.md",
                "Systems Language",
                "A fast language but not Rust specific.",
            ),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // Phrase "fast rust" — tokens must appear consecutively.
        // "consecutive.md" title is "Fast Rust" → consecutive.
        // "non_consecutive.md" has "fast" and "rust" but not adjacent.
        let results = index.score("\"fast rust\"", &stemmer);
        let paths: Vec<&str> = results.iter().map(|r| r.rel_path.as_str()).collect();
        assert!(
            paths.contains(&"consecutive.md"),
            "consecutive.md should match phrase: {paths:?}"
        );
        assert!(
            !paths.contains(&"non_consecutive.md"),
            "non_consecutive.md should not match phrase: {paths:?}"
        );
    }

    #[test]
    fn test_bm25_phrase_in_or_context() {
        let docs = vec![
            doc(
                "consecutive.md",
                "Fast Rust",
                "Rust is a fast systems language.",
            ),
            doc(
                "non_consecutive.md",
                "Systems Language",
                "A fast language but not Rust specific.",
            ),
            doc("cooking.md", "Cooking", "Recipes for healthy meals."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // Phrase "fast rust" in OR context: only docs with the phrase adjacently
        // should match the phrase part; cooking.md matches "cooking" via OR.
        let results = index.score("\"fast rust\" OR cooking", &stemmer);
        let paths: Vec<&str> = results.iter().map(|r| r.rel_path.as_str()).collect();
        assert!(
            paths.contains(&"consecutive.md"),
            "consecutive.md should match phrase in OR: {paths:?}"
        );
        assert!(
            paths.contains(&"cooking.md"),
            "cooking.md should match 'cooking' via OR: {paths:?}"
        );
        assert!(
            !paths.contains(&"non_consecutive.md"),
            "non_consecutive.md should NOT match phrase in OR (words not adjacent): {paths:?}"
        );
    }

    // ------------------------------------------------------------------
    // Negation via postings (no doc_token_sets)
    // ------------------------------------------------------------------

    #[test]
    fn test_bm25_negation_via_postings() {
        let docs = vec![
            doc("rust.md", "Rust", "Rust is a systems programming language."),
            doc(
                "python.md",
                "Python",
                "Python is a scripting programming language.",
            ),
            doc("go.md", "Go", "Go is a compiled programming language."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // "programming -python" should return rust.md and go.md but NOT python.md
        let results = index.score("programming -python", &stemmer);
        let paths: Vec<&str> = results.iter().map(|r| r.rel_path.as_str()).collect();
        assert!(
            !paths.contains(&"python.md"),
            "python.md should be excluded: {paths:?}"
        );
        assert!(
            paths.contains(&"rust.md"),
            "rust.md should remain: {paths:?}"
        );
        assert!(paths.contains(&"go.md"), "go.md should remain: {paths:?}");
    }

    #[test]
    fn test_bm25_negation_excludes_matching_docs() {
        let docs = vec![
            doc("rust.md", "Rust", "Rust is a systems programming language."),
            doc(
                "python.md",
                "Python",
                "Python is a scripting programming language.",
            ),
            doc("go.md", "Go", "Go is a compiled programming language."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("programming -python", &stemmer);
        let paths: Vec<&str> = results.iter().map(|r| r.rel_path.as_str()).collect();
        assert!(
            !paths.contains(&"python.md"),
            "python.md should be excluded: {paths:?}"
        );
        assert!(
            paths.contains(&"rust.md"),
            "rust.md should remain: {paths:?}"
        );
        assert!(paths.contains(&"go.md"), "go.md should remain: {paths:?}");
    }

    #[test]
    fn test_bm25_negation_only_returns_empty() {
        let docs = vec![doc("a.md", "Title", "Some body text.")];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        // Only negation terms → no positive terms → empty results
        let results = index.score("-text", &stemmer);
        assert!(
            results.is_empty(),
            "negation-only query should return empty"
        );
    }

    #[test]
    fn test_bm25_negation_with_stemming() {
        // "-running" should also exclude docs containing "run" (after stemming both)
        let docs = vec![
            doc("a.md", "Running", "I love running every day."),
            doc("b.md", "Swimming", "I love swimming every day."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("love -running", &stemmer);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].rel_path, "b.md");
    }

    // ------------------------------------------------------------------
    // Empty corpus
    // ------------------------------------------------------------------

    #[test]
    fn test_bm25_empty_corpus() {
        let index = Bm25InvertedIndex::build(vec![]);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("anything", &stemmer);
        assert!(results.is_empty());
    }

    // ------------------------------------------------------------------
    // build_from_tokens / build_from_entries
    // ------------------------------------------------------------------

    #[test]
    fn test_bm25_build_from_tokens() {
        let docs = vec![
            PreTokenizedInput {
                rel_path: "a.md".to_owned(),
                tokens: vec!["rust".to_owned(), "program".to_owned()].into(),
            },
            PreTokenizedInput {
                rel_path: "b.md".to_owned(),
                tokens: vec!["python".to_owned(), "program".to_owned()].into(),
            },
        ];
        let index = Bm25InvertedIndex::build_from_tokens(docs);
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("rust", &stemmer);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].rel_path, "a.md");
    }

    #[test]
    fn test_bm25_serde_round_trip() {
        let docs = vec![
            doc("rust.md", "Rust", "Rust is a systems programming language."),
            doc("python.md", "Python", "Python is a scripting language."),
        ];
        let index = Bm25InvertedIndex::build(docs);
        let stemmer = make_stemmer(StemLanguage::English);

        // Serialize to MessagePack and back.
        let bytes = rmp_serde::to_vec_named(&index).expect("serialize");
        let restored: Bm25InvertedIndex = rmp_serde::from_slice(&bytes).expect("deserialize");

        // Verify search results are identical after round-trip.
        let before = index.score("rust", &stemmer);
        let after = restored.score("rust", &stemmer);
        assert_eq!(before.len(), after.len());
        assert_eq!(before[0].rel_path, after[0].rel_path);
        // Use a relative tolerance — BM25 scores are sums of multiple f64
        // contributions, and HashMap iteration order (which differs between
        // runtimes — notably Miri vs. native) changes summation order,
        // introducing rounding differences around 1e-15. `f64::EPSILON`
        // (~2.22e-16) is too tight for summed scores; 1e-9 is well within
        // any meaningful score change and survives reordering.
        let rel_diff =
            (before[0].score - after[0].score).abs() / before[0].score.abs().max(f64::MIN_POSITIVE);
        assert!(
            rel_diff < 1e-9,
            "scores diverged: before={}, after={}, rel_diff={}",
            before[0].score,
            after[0].score,
            rel_diff
        );
    }

    #[test]
    fn test_bm25_build_from_entries() {
        use crate::index::IndexEntry;
        use indexmap::IndexMap;

        let entries = vec![
            IndexEntry {
                rel_path: "a.md".to_owned(),
                modified: String::new(),
                size: 0,
                lines: 0,
                properties: IndexMap::new(),
                tags: Vec::new(),
                sections: Vec::new(),
                tasks: Vec::new(),
                links: Vec::new(),
                self_anchors: Vec::new(),
                bm25_tokens: Some(vec!["rust".to_owned(), "program".to_owned()].into()),
                bm25_language: Some("english".to_owned()),
                bm25_tokenizer_version: Some(TOKENIZER_VERSION),
            },
            IndexEntry {
                rel_path: "b.md".to_owned(),
                modified: String::new(),
                size: 0,
                lines: 0,
                properties: IndexMap::new(),
                tags: Vec::new(),
                sections: Vec::new(),
                tasks: Vec::new(),
                links: Vec::new(),
                self_anchors: Vec::new(),
                bm25_tokens: None, // No tokens — should be skipped
                bm25_language: None,
                bm25_tokenizer_version: None,
            },
        ];

        let index = Bm25InvertedIndex::build_from_entries(&entries);
        assert!(index.is_some(), "should build from entries with tokens");
        let index = index.unwrap();
        let stemmer = make_stemmer(StemLanguage::English);
        let results = index.score("rust", &stemmer);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].rel_path, "a.md");
    }

    #[test]
    fn test_bm25_build_from_entries_none_when_no_tokens() {
        use crate::index::IndexEntry;
        use indexmap::IndexMap;

        let entries = vec![IndexEntry {
            rel_path: "a.md".to_owned(),
            modified: String::new(),
            size: 0,
            lines: 0,
            properties: IndexMap::new(),
            tags: Vec::new(),
            sections: Vec::new(),
            tasks: Vec::new(),
            links: Vec::new(),
            self_anchors: Vec::new(),
            bm25_tokens: None,
            bm25_language: None,
            bm25_tokenizer_version: None,
        }];

        assert!(
            Bm25InvertedIndex::build_from_entries(&entries).is_none(),
            "no tokens → should return None"
        );
    }

    #[test]
    fn test_bm25_index_tokenizer_version_matches_current_when_freshly_built() {
        let index = Bm25InvertedIndex::build(vec![DocumentInput {
            rel_path: "a.md".to_owned(),
            title: "Title".to_owned(),
            body: "Body text".to_owned(),
            language: StemLanguage::English,
            ..Default::default()
        }]);
        assert_eq!(index.tokenizer_version(), TOKENIZER_VERSION);
    }

    #[test]
    fn test_bm25_index_stale_tokenizer_version_is_detectable() {
        // Simulates a `Bm25InvertedIndex` persisted by an older hyalo build whose
        // `tokenize()` predates the CJK-bigram fix (F-2 / DEC-094). Readers must
        // compare `tokenizer_version()` against the current `TOKENIZER_VERSION`
        // and fall back to live re-tokenization rather than trust stale postings —
        // this only asserts the version is observably different, since the actual
        // fallback routing lives in the CLI's `find` command (see e2e coverage).
        let index = Bm25InvertedIndex::build(vec![DocumentInput {
            rel_path: "a.md".to_owned(),
            title: "Title".to_owned(),
            body: "Body text".to_owned(),
            language: StemLanguage::English,
            ..Default::default()
        }])
        .with_tokenizer_version_for_test(1);
        assert_ne!(index.tokenizer_version(), TOKENIZER_VERSION);
    }

    #[test]
    fn test_bm25_index_missing_tokenizer_version_field_deserializes_as_stale() {
        // A snapshot written before `tokenizer_version` existed serialized a map
        // with exactly these four keys and no `tokenizer_version`. `#[serde(default)]`
        // must decode that gap as `0`, which never equals `TOKENIZER_VERSION` —
        // proving old snapshots are detected as stale rather than silently trusted.
        #[derive(Serialize)]
        struct LegacyBm25IndexShim {
            postings: HashMap<String, Vec<Posting>>,
            doc_lengths: Vec<u32>,
            doc_paths: Vec<String>,
            avgdl: f64,
        }

        let legacy = LegacyBm25IndexShim {
            postings: HashMap::new(),
            doc_lengths: vec![3],
            doc_paths: vec!["a.md".to_owned()],
            avgdl: 3.0,
        };
        let bytes = rmp_serde::to_vec_named(&legacy).expect("serialize legacy shim");

        let reloaded: Bm25InvertedIndex =
            rmp_serde::from_slice(&bytes).expect("deserialize without tokenizer_version");
        assert_eq!(
            reloaded.tokenizer_version(),
            0,
            "field-absent snapshot must default to version 0, not the current version"
        );
        assert_ne!(reloaded.tokenizer_version(), TOKENIZER_VERSION);
    }

    // ------------------------------------------------------------------
    // is_low_discriminative
    // ------------------------------------------------------------------

    fn make_match(rel_path: &str, score: f64) -> Bm25Match {
        Bm25Match {
            rel_path: rel_path.to_owned(),
            score,
        }
    }

    #[test]
    fn test_low_discriminative_empty_matches_returns_false() {
        assert!(!is_low_discriminative(&[], 10));
    }

    #[test]
    fn test_low_discriminative_zero_total_docs_returns_false() {
        let matches = vec![make_match("a.md", 0.5)];
        assert!(!is_low_discriminative(&matches, 0));
    }

    #[test]
    fn test_low_discriminative_high_ratio_low_scores_returns_true() {
        // 9 matches out of 10 docs = 90% ratio; all scores below 1.0
        let matches: Vec<Bm25Match> = (0..9)
            .map(|i| make_match(&format!("{i}.md"), 0.5))
            .collect();
        assert!(is_low_discriminative(&matches, 10));
    }

    #[test]
    fn test_low_discriminative_low_ratio_returns_false() {
        // 3 matches out of 10 docs = 30% ratio → not low discriminative
        let matches: Vec<Bm25Match> = (0..3)
            .map(|i| make_match(&format!("{i}.md"), 0.5))
            .collect();
        assert!(!is_low_discriminative(&matches, 10));
    }

    #[test]
    fn test_low_discriminative_high_ratio_high_scores_returns_false() {
        // 9 matches out of 10 docs = 90% ratio, but top score >= 1.0 → not low discriminative
        let mut matches: Vec<Bm25Match> = (0..8)
            .map(|i| make_match(&format!("{i}.md"), 0.5))
            .collect();
        matches.push(make_match("high.md", 2.5));
        assert!(!is_low_discriminative(&matches, 10));
    }

    // ------------------------------------------------------------------
    // query_is_operator_only
    // ------------------------------------------------------------------

    #[test]
    fn test_query_is_operator_only_and() {
        assert!(
            query_is_operator_only("and"),
            "bare 'and' should be operator-only"
        );
        assert!(
            query_is_operator_only("AND"),
            "case-insensitive 'AND' should be operator-only"
        );
    }

    #[test]
    fn test_query_is_operator_only_or() {
        assert!(
            query_is_operator_only("or"),
            "bare 'or' should be operator-only"
        );
        assert!(
            query_is_operator_only("OR"),
            "case-insensitive 'OR' should be operator-only"
        );
    }

    #[test]
    fn test_query_is_operator_only_multiple_operators() {
        assert!(
            query_is_operator_only("and or"),
            "multiple operator keywords should be operator-only"
        );
        assert!(
            query_is_operator_only("or and"),
            "reversed order should still be operator-only"
        );
    }

    #[test]
    fn test_query_is_operator_only_mixed_returns_false() {
        assert!(
            !query_is_operator_only("rust and"),
            "mixed query should not be operator-only"
        );
        assert!(
            !query_is_operator_only("foo OR bar"),
            "query with real terms should not be operator-only"
        );
    }

    #[test]
    fn test_query_is_operator_only_plain_word_returns_false() {
        assert!(!query_is_operator_only("rust"), "'rust' is not an operator");
        assert!(
            !query_is_operator_only("not"),
            "'not' is not handled as a boolean operator"
        );
    }

    #[test]
    fn test_query_is_operator_only_empty_returns_false() {
        assert!(
            !query_is_operator_only(""),
            "empty query should return false"
        );
        assert!(
            !query_is_operator_only("   "),
            "whitespace-only query should return false"
        );
    }
}

#[cfg(test)]
mod iteration292_tests {
    use super::*;

    #[test]
    fn independent_flat_clause_evaluator_matches_small_authored_corpus() {
        // The reference evaluator scans token windows directly; it does not use
        // posting intersection, positional lookup or the production query parser.
        let bodies = [
            "green red x blue",
            "red",
            "red blue",
            "neither",
            "rust memory allocation",
            "rust memory safety",
            "rust memory\nsafety",
            "red red blue",
        ];
        let stemmer = create_stemmer(StemLanguage::English);
        let corpus = Bm25InvertedIndex::build(
            bodies
                .iter()
                .enumerate()
                .map(|(i, body)| DocumentInput {
                    rel_path: format!("{i}.md"),
                    title: String::new(),
                    body: (*body).into(),
                    language: StemLanguage::English,
                    ..Default::default()
                })
                .collect(),
        );
        let atoms = [
            "red",
            "green",
            "\"red blue\"",
            "rust",
            "\"memory safety\"",
            "\"red red\"",
            "the",
        ];
        for left in atoms {
            for right in atoms {
                for or in [false, true] {
                    for negative in ["", "red", "\"memory safety\""] {
                        let query = format!(
                            "{left} {} {right} {}",
                            if or { "OR" } else { "AND" },
                            if negative.is_empty() {
                                String::new()
                            } else {
                                format!("-{negative}")
                            }
                        );
                        let mut expected = Vec::new();
                        for (id, body) in bodies.iter().enumerate() {
                            let tokens = tokenize(body, &stemmer);
                            let matches = |atom: &str| {
                                let needle = tokenize(atom.trim_matches('"'), &stemmer);
                                !needle.is_empty()
                                    && tokens.windows(needle.len()).any(|window| window == needle)
                            };
                            let positive = if or {
                                matches(left) || matches(right)
                            } else {
                                matches(left) && matches(right)
                            };
                            if positive && (negative.is_empty() || !matches(negative)) {
                                expected.push(format!("{id}.md"));
                            }
                        }
                        let mut actual: Vec<_> = corpus
                            .score(&query, &stemmer)
                            .into_iter()
                            .map(|hit| hit.rel_path)
                            .collect();
                        actual.sort();
                        expected.sort();
                        assert_eq!(actual, expected, "{query}");
                    }
                }
            }
        }
        let or_hits = corpus.score("\"red blue\" OR green", &stemmer);
        let green = corpus.score("green", &stemmer);
        assert_eq!(
            or_hits
                .iter()
                .find(|hit| hit.rel_path == "0.md")
                .unwrap()
                .score
                .to_bits(),
            green[0].score.to_bits()
        );
    }

    #[test]
    fn independent_boolean_reference_covers_language_precedence() {
        use StemLanguage::{English, German};
        // Expected precedence is authored here, independently of resolve_language.
        let settings = [
            (None, None, English),
            (None, Some("german"), German),
            (Some("english"), Some("german"), English),
            (Some("german"), Some("english"), German),
        ];
        let documents = [
            (None, "running fast"),
            (Some("english"), "running fast safely"),
            (Some("german"), "Häuser Häuser running"),
            (Some("invalid"), "the running slow"),
        ];
        assert_ne!(
            tokenize("running", &create_stemmer(English)),
            tokenize("running", &create_stemmer(German))
        );
        for (cli, config, expected_query_language) in settings {
            assert_eq!(resolve_language(None, cli, config), expected_query_language);
            let expected_languages: Vec<_> = documents
                .iter()
                .map(|(fm, _)| match fm {
                    Some("english") => English,
                    Some("german") => German,
                    _ => expected_query_language,
                })
                .collect();
            let corpus = Bm25InvertedIndex::build(
                documents
                    .iter()
                    .enumerate()
                    .map(|(i, (fm, body))| {
                        let language = resolve_language(*fm, cli, config);
                        assert_eq!(language, expected_languages[i]);
                        DocumentInput {
                            rel_path: format!("{i}.md"),
                            title: String::new(),
                            body: (*body).into(),
                            language,
                            ..Default::default()
                        }
                    })
                    .collect(),
            );
            for (left, right, either, negative) in [
                ("run", "fast", false, ""),
                ("running fast", "Häuser Häuser", true, "running slow"),
                ("the", "running", true, "fast safely"),
                ("Häuser Häuser", "running", false, ""),
            ] {
                let query = format!(
                    "\"{left}\" {} \"{right}\" {}",
                    if either { "OR" } else { "AND" },
                    if negative.is_empty() {
                        String::new()
                    } else {
                        format!("-\"{negative}\"")
                    }
                );
                let query_stemmer = create_stemmer(expected_query_language);
                let mut expected = Vec::new();
                for (i, (_, body)) in documents.iter().enumerate() {
                    let tokens = tokenize(body, &create_stemmer(expected_languages[i]));
                    let matches = |atom: &str| {
                        let needle = tokenize(atom, &query_stemmer);
                        !needle.is_empty()
                            && tokens.windows(needle.len()).any(|window| window == needle)
                    };
                    let positive = if either {
                        matches(left) || matches(right)
                    } else {
                        matches(left) && matches(right)
                    };
                    if positive && (negative.is_empty() || !matches(negative)) {
                        expected.push(format!("{i}.md"));
                    }
                }
                let mut actual: Vec<_> = corpus
                    .score_compiled(&CompiledQuery::new(&query, expected_query_language))
                    .into_iter()
                    .map(|hit| hit.rel_path)
                    .collect();
                expected.sort();
                actual.sort();
                assert_eq!(actual, expected, "{cli:?}/{config:?}: {query}");
            }
        }
    }

    #[test]
    fn checked_expansion_budget_rejects_term_position_product() {
        let corpus = Bm25InvertedIndex::new_for_test(
            HashMap::from([(
                "x".repeat(128),
                vec![Posting {
                    doc_id: 0,
                    term_freq: 32,
                    positions: (0..32).collect(),
                    ..Default::default()
                }],
            )]),
            vec![32],
            vec!["a.md".into()],
            32.0,
        );
        assert!(!corpus.expansion_within_budget(1024));
        assert!(corpus.expansion_within_budget(8192));
        assert_eq!(
            corpus.reconstruct_all_tokens().unwrap()["a.md"]
                .tokens
                .len(),
            32
        );
    }
    #[test]
    fn compact_scoring_and_selected_reconstruction_have_separate_budgets() {
        let long = "x".repeat(128);
        let corpus = Bm25InvertedIndex::build_from_tokens(vec![
            PreTokenizedInput {
                rel_path: "large.md".into(),
                tokens: vec![long.clone(); 32].into(),
            },
            PreTokenizedInput {
                rel_path: "small.md".into(),
                tokens: vec!["small".into()].into(),
            },
        ]);
        assert!(!corpus.expansion_within_budget(1024));
        assert!(
            corpus
                .reconstruct_tokens_with_budget(|_| true, 1024)
                .is_err()
        );
        let selected = corpus
            .reconstruct_tokens_with_budget(|path| path == "small.md", 1024)
            .unwrap();
        assert_eq!(selected["small.md"].tokens, vec!["small"]);
        let stemmer = Stemmer::create(rust_stemmers::Algorithm::English);
        let scored = corpus.score(&long, &stemmer);
        assert_eq!(scored.len(), 1);
        assert_eq!(scored[0].rel_path, "large.md");
    }
}
