//! Common-English-word detection for auto-link candidate titles (iter-197).
//!
//! `hyalo links auto` turns every page title into a match candidate. On vaults
//! whose page titles double as ordinary English words — `permissions.md`,
//! `index.md`, `notes.md` — that produces prose-mention noise: linking the word
//! "permissions" in a how-to guide to the permissions page is almost never what
//! the author meant. `[links.auto] exclude_titles` (iter-195a) fixes it once the
//! user has noticed, but a first run has no way to tell them.
//!
//! This module answers one narrow question — *is this title an ordinary English
//! word (or a generic documentation filename)?* — so the CLI can raise an
//! advisory `note:` naming the offenders. It is deliberately a bundled static
//! list rather than a dictionary dependency: predictable, allocation-free, no
//! new crate in the tree, and small enough to read.
//!
//! The list holds high-frequency English words plus generic doc filenames
//! (`readme`, `changelog`, `index`, …) and the four platform/format names that
//! show up as note titles in almost every vault while being prose nouns
//! everywhere else (`github`, `gitlab`, `markdown`, `wiki` — iter-267, UX-9).
//! The list stays deliberately narrow there: product and domain nouns a vault
//! genuinely links to (`Obsidian`, `Dataview`, `Canvas`) and words that are
//! plausible page titles in their own right (`config`, `setup`, `template`)
//! are absent, because the frequency trigger already catches the ones that
//! actually flood a run. Words shorter than 3 characters are
//! omitted because `links auto --min-length` defaults to 3 and never proposes
//! them anyway.
//!
//! Matching is case-insensitive and covers regular plurals, so the title
//! "Permissions" is recognised from the stored `permission`.

/// High-frequency English words plus generic documentation filenames.
///
/// Invariants (enforced by unit tests): ASCII lowercase, sorted, deduplicated,
/// every entry at least 3 characters long. Sortedness is what makes
/// [`is_common_word`] a binary search.
static COMMON_WORDS: &[&str] = &[
    "about",
    "above",
    "access",
    "account",
    "action",
    "active",
    "activity",
    "actually",
    "address",
    "after",
    "again",
    "against",
    "agree",
    "ahead",
    "all",
    "allow",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "although",
    "always",
    "among",
    "amount",
    "another",
    "answer",
    "any",
    "anyone",
    "anything",
    "appear",
    "apply",
    "approach",
    "area",
    "argue",
    "around",
    "arrive",
    "article",
    "ask",
    "assume",
    "attention",
    "author",
    "available",
    "avoid",
    "away",
    "back",
    "bad",
    "base",
    "basic",
    "because",
    "become",
    "before",
    "begin",
    "behind",
    "being",
    "believe",
    "below",
    "benefit",
    "best",
    "better",
    "between",
    "beyond",
    "big",
    "body",
    "book",
    "both",
    "break",
    "bring",
    "build",
    "business",
    "but",
    "buy",
    "call",
    "can",
    "capacity",
    "care",
    "carry",
    "case",
    "catch",
    "cause",
    "center",
    "central",
    "certain",
    "chance",
    "change",
    "changelog",
    "character",
    "charge",
    "check",
    "child",
    "choice",
    "choose",
    "claim",
    "class",
    "clear",
    "close",
    "code",
    "collect",
    "color",
    "come",
    "comment",
    "common",
    "community",
    "company",
    "compare",
    "complete",
    "computer",
    "concern",
    "condition",
    "consider",
    "contain",
    "content",
    "context",
    "continue",
    "contributing",
    "control",
    "cost",
    "could",
    "count",
    "country",
    "couple",
    "course",
    "cover",
    "create",
    "current",
    "customer",
    "data",
    "day",
    "deal",
    "decide",
    "decision",
    "deep",
    "default",
    "degree",
    "deliver",
    "demand",
    "depend",
    "describe",
    "design",
    "detail",
    "determine",
    "develop",
    "device",
    "difference",
    "different",
    "difficult",
    "direct",
    "direction",
    "discuss",
    "display",
    "document",
    "does",
    "done",
    "door",
    "doubt",
    "down",
    "draw",
    "drive",
    "drop",
    "during",
    "each",
    "early",
    "easy",
    "economy",
    "edge",
    "effect",
    "effort",
    "either",
    "element",
    "else",
    "end",
    "energy",
    "enough",
    "enter",
    "entire",
    "environment",
    "error",
    "especially",
    "establish",
    "even",
    "event",
    "ever",
    "every",
    "everyone",
    "everything",
    "exactly",
    "example",
    "exist",
    "expect",
    "experience",
    "explain",
    "express",
    "face",
    "fact",
    "factor",
    "fail",
    "fall",
    "family",
    "faq",
    "far",
    "fast",
    "feature",
    "feel",
    "few",
    "field",
    "figure",
    "file",
    "fill",
    "final",
    "find",
    "fine",
    "finish",
    "fire",
    "first",
    "fit",
    "five",
    "focus",
    "follow",
    "force",
    "foreign",
    "forget",
    "form",
    "forward",
    "four",
    "free",
    "friend",
    "from",
    "front",
    "full",
    "function",
    "fund",
    "future",
    "game",
    "general",
    "generate",
    "get",
    "getting-started",
    "girl",
    "github",
    "gitlab",
    "give",
    "glass",
    "goal",
    "good",
    "government",
    "great",
    "green",
    "group",
    "grow",
    "guess",
    "guide",
    "half",
    "hand",
    "happen",
    "hard",
    "have",
    "head",
    "health",
    "hear",
    "heart",
    "heavy",
    "help",
    "here",
    "high",
    "history",
    "hold",
    "home",
    "hope",
    "hour",
    "house",
    "how",
    "however",
    "huge",
    "human",
    "idea",
    "identify",
    "image",
    "imagine",
    "impact",
    "important",
    "improve",
    "include",
    "increase",
    "indeed",
    "index",
    "indicate",
    "individual",
    "industry",
    "information",
    "inside",
    "instead",
    "interest",
    "internal",
    "into",
    "issue",
    "item",
    "join",
    "just",
    "keep",
    "key",
    "kind",
    "know",
    "knowledge",
    "land",
    "language",
    "large",
    "last",
    "late",
    "later",
    "laugh",
    "law",
    "lead",
    "learn",
    "leave",
    "left",
    "legal",
    "length",
    "less",
    "let",
    "letter",
    "level",
    "licence",
    "license",
    "life",
    "light",
    "like",
    "likely",
    "limit",
    "line",
    "link",
    "list",
    "listen",
    "little",
    "live",
    "load",
    "local",
    "log",
    "long",
    "look",
    "lose",
    "loss",
    "lot",
    "love",
    "low",
    "machine",
    "main",
    "maintain",
    "major",
    "make",
    "manage",
    "management",
    "manager",
    "many",
    "markdown",
    "market",
    "material",
    "matter",
    "maybe",
    "mean",
    "measure",
    "media",
    "meet",
    "member",
    "memory",
    "mention",
    "message",
    "method",
    "middle",
    "might",
    "mind",
    "minute",
    "miss",
    "mission",
    "model",
    "modern",
    "moment",
    "money",
    "month",
    "more",
    "most",
    "mother",
    "move",
    "much",
    "music",
    "must",
    "name",
    "nation",
    "national",
    "natural",
    "nature",
    "near",
    "nearly",
    "necessary",
    "need",
    "network",
    "never",
    "new",
    "news",
    "next",
    "nice",
    "night",
    "none",
    "nor",
    "normal",
    "north",
    "note",
    "notes",
    "nothing",
    "notice",
    "now",
    "number",
    "object",
    "obtain",
    "obvious",
    "occur",
    "off",
    "offer",
    "office",
    "official",
    "often",
    "old",
    "once",
    "one",
    "online",
    "only",
    "open",
    "operation",
    "opportunity",
    "option",
    "order",
    "organization",
    "other",
    "out",
    "output",
    "outside",
    "over",
    "overview",
    "own",
    "page",
    "paper",
    "parent",
    "part",
    "particular",
    "partner",
    "party",
    "pass",
    "past",
    "pattern",
    "pay",
    "people",
    "per",
    "perform",
    "perhaps",
    "period",
    "permission",
    "person",
    "personal",
    "phone",
    "pick",
    "picture",
    "piece",
    "place",
    "plan",
    "plant",
    "play",
    "please",
    "point",
    "policy",
    "political",
    "poor",
    "popular",
    "position",
    "possible",
    "power",
    "practice",
    "prepare",
    "present",
    "president",
    "press",
    "pressure",
    "pretty",
    "prevent",
    "price",
    "primary",
    "private",
    "probably",
    "problem",
    "process",
    "produce",
    "product",
    "program",
    "project",
    "property",
    "protect",
    "prove",
    "provide",
    "public",
    "pull",
    "purpose",
    "push",
    "put",
    "quality",
    "question",
    "quick",
    "quickly",
    "quite",
    "race",
    "raise",
    "range",
    "rate",
    "rather",
    "reach",
    "read",
    "readme",
    "ready",
    "real",
    "reality",
    "realize",
    "really",
    "reason",
    "receive",
    "recent",
    "recently",
    "recognize",
    "record",
    "reduce",
    "refer",
    "reference",
    "reflect",
    "region",
    "relate",
    "relationship",
    "release",
    "remain",
    "remember",
    "remove",
    "repeat",
    "replace",
    "report",
    "represent",
    "require",
    "research",
    "resource",
    "respond",
    "response",
    "responsibility",
    "rest",
    "result",
    "return",
    "reveal",
    "review",
    "rich",
    "right",
    "rise",
    "risk",
    "road",
    "role",
    "room",
    "rule",
    "run",
    "safe",
    "same",
    "save",
    "say",
    "scale",
    "scene",
    "school",
    "science",
    "score",
    "search",
    "season",
    "seat",
    "second",
    "section",
    "security",
    "see",
    "seek",
    "seem",
    "sell",
    "send",
    "sense",
    "series",
    "serious",
    "serve",
    "service",
    "set",
    "setting",
    "seven",
    "several",
    "share",
    "short",
    "should",
    "show",
    "side",
    "sign",
    "significant",
    "similar",
    "simple",
    "simply",
    "since",
    "single",
    "site",
    "situation",
    "six",
    "size",
    "skill",
    "small",
    "social",
    "society",
    "some",
    "someone",
    "something",
    "sometimes",
    "soon",
    "sort",
    "sound",
    "source",
    "space",
    "speak",
    "special",
    "specific",
    "speed",
    "spend",
    "staff",
    "stage",
    "stand",
    "standard",
    "star",
    "start",
    "state",
    "statement",
    "station",
    "stay",
    "step",
    "still",
    "stop",
    "store",
    "story",
    "strategy",
    "street",
    "strong",
    "structure",
    "student",
    "study",
    "stuff",
    "style",
    "subject",
    "success",
    "such",
    "suddenly",
    "suggest",
    "summary",
    "support",
    "suppose",
    "sure",
    "surface",
    "system",
    "table",
    "take",
    "talk",
    "target",
    "task",
    "teach",
    "team",
    "technology",
    "tell",
    "term",
    "test",
    "text",
    "than",
    "thank",
    "that",
    "the",
    "their",
    "them",
    "themselves",
    "then",
    "theory",
    "there",
    "these",
    "they",
    "thing",
    "think",
    "third",
    "this",
    "those",
    "though",
    "thought",
    "three",
    "through",
    "throughout",
    "time",
    "today",
    "todo",
    "together",
    "tone",
    "too",
    "tool",
    "top",
    "total",
    "touch",
    "toward",
    "town",
    "trade",
    "traditional",
    "train",
    "travel",
    "treat",
    "tree",
    "trial",
    "trip",
    "trouble",
    "true",
    "trust",
    "truth",
    "try",
    "turn",
    "two",
    "type",
    "under",
    "understand",
    "unit",
    "until",
    "update",
    "upon",
    "use",
    "user",
    "usually",
    "value",
    "various",
    "version",
    "very",
    "view",
    "visit",
    "voice",
    "vote",
    "wait",
    "walk",
    "wall",
    "want",
    "watch",
    "water",
    "way",
    "weather",
    "week",
    "weight",
    "well",
    "west",
    "what",
    "whatever",
    "when",
    "where",
    "whether",
    "which",
    "while",
    "white",
    "who",
    "whole",
    "whom",
    "whose",
    "why",
    "wide",
    "wiki",
    "will",
    "win",
    "window",
    "wish",
    "with",
    "within",
    "without",
    "woman",
    "wonder",
    "word",
    "work",
    "worker",
    "world",
    "worry",
    "would",
    "write",
    "wrong",
    "year",
    "yes",
    "yet",
    "you",
    "young",
    "your",
    "yourself",
];

/// Shortest title this module can classify.
///
/// Mirrors the `links auto --min-length` default: shorter titles are never
/// proposed as candidates, so they are never asked about.
pub const MIN_COMMON_WORD_LEN: usize = 3;

/// `true` when `title` is an ordinary English word or a generic documentation
/// filename, and therefore a likely source of auto-link noise.
///
/// Case-insensitive. Regular plurals resolve to their singular before the
/// lookup, so `"Permissions"` is recognised from the stored `permission`:
///
/// - `-ies` → `-y` (`policies` → `policy`)
/// - `-es`  → `-` and `-s` → `-` (`processes` → `process`, `notes` → `note`)
///
/// Non-ASCII titles always return `false`: the list is an English word list and
/// lowercasing non-ASCII correctly is not worth the allocation for a heuristic
/// whose only job is to phrase an advisory note.
///
/// ```
/// use hyalo_core::is_common_word;
/// assert!(is_common_word("permissions"));
/// assert!(is_common_word("README"));
/// assert!(!is_common_word("Kubernetes"));
/// ```
#[must_use]
pub fn is_common_word(title: &str) -> bool {
    let title = title.trim();
    if title.len() < MIN_COMMON_WORD_LEN || !title.is_ascii() {
        return false;
    }
    let lower = title.to_ascii_lowercase();
    if contains(&lower) {
        return true;
    }
    // Regular plurals: try the singular forms, longest suffix first.
    if let Some(stem) = lower.strip_suffix("ies") {
        let mut singular = String::with_capacity(stem.len() + 1);
        singular.push_str(stem);
        singular.push('y');
        if contains(&singular) {
            return true;
        }
    }
    if let Some(stem) = lower.strip_suffix("es")
        && contains(stem)
    {
        return true;
    }
    if let Some(stem) = lower.strip_suffix('s')
        && contains(stem)
    {
        return true;
    }
    false
}

/// Binary search over the sorted static list.
fn contains(needle: &str) -> bool {
    COMMON_WORDS.binary_search(&needle).is_ok()
}

#[cfg(test)]
mod tests {
    use super::{COMMON_WORDS, MIN_COMMON_WORD_LEN, is_common_word};

    #[test]
    fn word_list_is_sorted_deduplicated_and_lowercase() {
        for pair in COMMON_WORDS.windows(2) {
            assert!(
                pair[0] < pair[1],
                "COMMON_WORDS must be sorted and deduplicated: {:?} !< {:?}",
                pair[0],
                pair[1]
            );
        }
        for word in COMMON_WORDS {
            assert!(
                word.is_ascii() && *word == word.to_ascii_lowercase(),
                "COMMON_WORDS entries must be ASCII lowercase: {word:?}"
            );
            assert!(
                word.len() >= MIN_COMMON_WORD_LEN,
                "COMMON_WORDS entries must be at least {MIN_COMMON_WORD_LEN} chars: {word:?}"
            );
        }
    }

    #[test]
    fn matches_plain_words_case_insensitively() {
        assert!(is_common_word("index"));
        assert!(is_common_word("Index"));
        assert!(is_common_word("INDEX"));
        assert!(is_common_word("  note  "));
    }

    #[test]
    fn matches_generic_doc_filenames() {
        for name in ["readme", "README", "changelog", "todo", "license"] {
            assert!(is_common_word(name), "{name} should be a common title");
        }
    }

    #[test]
    fn matches_regular_plurals() {
        assert!(is_common_word("permissions"));
        assert!(is_common_word("notes"));
        assert!(is_common_word("processes"));
        assert!(is_common_word("policies"));
    }

    #[test]
    fn rejects_domain_specific_titles() {
        for title in [
            "Kubernetes",
            "hyalo",
            "frontmatter",
            "wikilink",
            "Corina",
            "aho-corasick",
        ] {
            assert!(!is_common_word(title), "{title} should not be common");
        }
    }

    #[test]
    fn rejects_short_and_empty_titles() {
        assert!(!is_common_word(""));
        assert!(!is_common_word("of"));
        assert!(!is_common_word("a"));
        assert!(!is_common_word("  "));
    }

    #[test]
    fn rejects_non_ascii_titles() {
        // The list is English-only; a non-ASCII title is never classified.
        assert!(!is_common_word("Übersicht"));
        assert!(!is_common_word("données"));
    }

    #[test]
    fn plural_stripping_does_not_invent_words() {
        // "ss" must not be stripped down to a match that isn't there.
        assert!(!is_common_word("zzz"));
        assert!(!is_common_word("zzzs"));
    }
}
