// Generated by `cargo run -p xtask -- generate-ts-types`; do not edit.

export type * from "./generated/index.js";

import type { ConfigResult } from "./generated/ConfigResult.js";
import type { FileObject } from "./generated/FileObject.js";
import type { FindArgs } from "./generated/FindArgs.js";
import type { GlobalArgs } from "./generated/GlobalArgs.js";
import type { ReadArgs } from "./generated/ReadArgs.js";
import type { ReadResult } from "./generated/ReadResult.js";
import type { SummaryArgs } from "./generated/SummaryArgs.js";
import type { VaultSummary } from "./generated/VaultSummary.js";

type ApiGlobals = Partial<Omit<GlobalArgs, "format" | "jq" | "count" | "hints" | "no_hints">>;
export type FindOptions = ApiGlobals & Partial<Omit<FindArgs, "filenames_only" | "filenames0" | "strict">>;
export type ReadOptions = ApiGlobals & Partial<ReadArgs>;
export type SummaryOptions = ApiGlobals & Partial<SummaryArgs>;
export type ConfigOptions = ApiGlobals;

export type FindResult = Array<FileObject>;
export type SummaryResult = Omit<VaultSummary, "dir">;
export type { ConfigResult, ReadResult };
