use std::collections::HashMap;
use std::fmt::Write as _;

use jaq_core::{Native, data};
use jaq_json::Val;
use serde::Serialize;
use serde_json::json;

// ---------------------------------------------------------------------------
// Filter cache
// ---------------------------------------------------------------------------

/// The `DataT` implementation used for jaq filter compilation and execution.
///
/// `JustLut<Val>` is a minimal wrapper that only provides the compiled lookup
/// table — sufficient because we don't use lifetime-dependent filters like
/// `inputs`.
type D = data::JustLut<Val>;

/// Cache of compiled jaq filters, keyed by filter source string.
///
/// The compiled `Filter` is fully owned (no lifetime parameters) and `Clone`,
/// so it can be stored directly in a `HashMap`. The `Arena` used during
/// `Loader::load` is a temporary scratch pad — once `compile` returns, the
/// `Filter` no longer borrows from it.
type JaqFilterCache = HashMap<String, jaq_core::compile::Filter<Native<D>>>;

/// Output format.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum Format {
    Json,
    Text,
    /// GitHub Actions workflow-command output. Lint-only: emits one
    /// `::error`/`::warning file=…,line=…,title=…::message` line per violation
    /// so findings render as inline PR annotations. Non-lint commands reject it.
    Github,
}

impl std::fmt::Display for Format {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Format::Json => f.write_str("json"),
            Format::Text => f.write_str("text"),
            Format::Github => f.write_str("github"),
        }
    }
}

/// Result of a command execution: either success (exit 0) or a user-facing error (exit 1).
/// Internal/unexpected errors are represented by `anyhow::Error` at the call site.
///
/// **Invariant**: `Success.output` must always be a valid JSON string — the pipeline handles
/// format conversion. Commands must never store pre-formatted text here.
///
/// For commands like `read` whose text output is raw file content (not structured data),
/// use `RawOutput` to bypass the JSON pipeline entirely.
#[derive(Debug)]
pub enum CommandOutcome {
    /// Successful operation — JSON output goes to stdout via the pipeline.
    Success {
        /// Always-valid JSON string (bare array, object, etc.). Never pre-formatted text.
        output: String,
        /// Optional total item count for pagination display.
        total: Option<u64>,
    },
    /// Raw text output, bypasses the JSON pipeline — printed directly to stdout as-is.
    /// Used by `read` command for text-format content output.
    RawOutput(String),
    /// Raw byte output, bypasses the JSON pipeline *and* the control-character
    /// sanitizer — written to stdout verbatim (iter-238). Used by
    /// `find --filenames0`, whose NUL delimiters are the entire point of the
    /// projection: NUL is a control character, so the text-oriented
    /// sanitization applied to [`CommandOutcome::RawOutput`] would strip it.
    /// Only producers whose content is generated by hyalo itself (vault-relative
    /// paths) belong here — never raw file body text.
    RawBytes(Vec<u8>),
    /// User error (file not found, property missing, etc.) — output goes to stderr.
    UserError(String),
}

impl CommandOutcome {
    /// Construct a successful outcome carrying a JSON string with no total count.
    #[must_use]
    pub fn success(output: String) -> Self {
        Self::Success {
            output,
            total: None,
        }
    }

    /// Construct a successful outcome carrying a JSON string with a total item count.
    #[must_use]
    pub fn success_with_total(output: String, total: u64) -> Self {
        Self::Success {
            output,
            total: Some(total),
        }
    }

    /// Extract the output string from `Success` or `RawOutput`, or panic.
    ///
    /// Intended for use in unit tests where the command is expected to succeed.
    #[cfg(test)]
    #[must_use]
    pub fn unwrap_output(self) -> String {
        match self {
            Self::Success { output, .. } | Self::RawOutput(output) => output,
            Self::RawBytes(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
            Self::UserError(msg) => panic!("expected success, got UserError: {msg}"),
        }
    }
}

impl Format {
    #[must_use]
    pub fn from_str_opt(s: &str) -> Option<Self> {
        match s {
            "json" => Some(Self::Json),
            "text" => Some(Self::Text),
            _ => None,
        }
    }
}

/// Strip control characters that could inject terminal escape sequences.
///
/// Removes bytes 0x00-0x08, 0x0B-0x0C, 0x0E-0x1F, 0x7F, and 0x9B-0x9F
/// (C0/C1 control codes minus `\n` (0x0A) and `\t` (0x09)).
///
/// `pub(crate)` so `CommandOutcome::RawOutput` print sites (which bypass the
/// JSON pipeline and therefore never pass through [`format_success`] /
/// [`format_envelope`]) can sanitize file-derived content before writing it
/// to the terminal — see `output_pipeline.rs` and `run.rs`.
pub(crate) fn sanitize_control_chars(s: &str) -> String {
    s.chars()
        .filter(|&c| {
            // Keep printable chars, newline, and tab
            !c.is_control() || c == '\n' || c == '\t'
        })
        .collect()
}

/// Format a successful JSON value for output.
#[must_use]
pub fn format_success(format: Format, value: &serde_json::Value) -> String {
    match format {
        // `Github` is rendered by the output pipeline (lint-only); if it ever
        // reaches a generic formatter, fall back to JSON rather than panicking.
        Format::Json | Format::Github => serde_json::to_string_pretty(value)
            .expect("serializing serde_json::Value is infallible"),
        Format::Text => {
            let mut cache = JaqFilterCache::new();
            sanitize_control_chars(&format_value_as_text(value, &mut cache))
        }
    }
}

/// Format any `Serialize` type for output.
///
/// Converts the value to `serde_json::Value` first so that the text formatter
/// can operate on a uniform representation.
#[must_use]
pub fn format_output<T: Serialize>(format: Format, value: &T) -> String {
    let json = serde_json::to_value(value).expect("derived Serialize impl should not fail");
    format_success(format, &json)
}

/// Serialize one hint for the JSON envelope.
///
/// `writes` is always present (never omitted when `false`) so a consumer can
/// filter on it without having to distinguish "absent" from "read-only"
/// (iter-201, M-7).
fn hint_to_json(hint: &crate::hints::Hint) -> serde_json::Value {
    serde_json::json!({
        "description": &hint.description,
        "cmd": &hint.cmd,
        "writes": hint.writes,
    })
}

/// Append the `-> hyalo …` drill-down block to text output.
///
/// Mutating suggestions are rendered with a distinct `=>` arrow and a trailing
/// `[writes]` tag. Before iter-201 a `views set …` command — which rewrites
/// `.hyalo.toml` — appeared in the same `->` list as read-only drill-downs,
/// so "run the hints" was not a safe instruction to give an agent.
fn append_hint_lines(text: &mut String, hints: &[crate::hints::Hint]) {
    if hints.is_empty() {
        return;
    }
    // Blank separator line only when there IS a body to separate from.
    // iter-267 (UX-13): a zero-result run has no body, and the unconditional
    // separator opened its stdout with two blank lines before the first hint.
    if !text.is_empty() {
        text.push_str("\n\n");
    }
    for (i, hint) in hints.iter().enumerate() {
        if i > 0 {
            text.push('\n');
        }
        if hint.cmd.is_empty() {
            // Advice-only hint (no follow-up command). Render the
            // description directly without the `cmd  # desc` layout.
            text.push_str("  -> ");
            text.push_str(&hint.description);
        } else if hint.writes {
            text.push_str("  => ");
            text.push_str(&hint.cmd);
            text.push_str("  # ");
            text.push_str(&hint.description);
            text.push_str(" [writes]");
        } else {
            text.push_str("  -> ");
            text.push_str(&hint.cmd);
            text.push_str("  # ");
            text.push_str(&hint.description);
        }
    }
}

/// Build the JSON envelope value: `{"results": ..., "total": <optional>, "hints": [...]}`.
///
/// The envelope is always present even when hints is empty (hints becomes `[]`).
/// `total` is included only when `Some`.
#[must_use]
pub fn build_envelope_value(
    value: &serde_json::Value,
    total: Option<u64>,
    hints: &[crate::hints::Hint],
) -> serde_json::Value {
    let hints_json: Vec<serde_json::Value> = hints.iter().map(hint_to_json).collect();
    let mut envelope = serde_json::json!({
        "results": value,
        "hints": hints_json,
    });
    if let Some(t) = total {
        envelope["total"] = serde_json::json!(t);
    }
    // Hoist a top-level `dir` field when results carry one (e.g. `summary`),
    // so consumers can read it without traversing into `results`. This matches
    // the shape of `hyalo config --format json`, which surfaces `dir` at the
    // top level. After hoisting, strip `dir` from the inner results so it
    // is not duplicated at both `.dir` and `.results.dir` (NEW-5).
    if let Some(dir) = value
        .as_object()
        .and_then(|o| o.get("dir"))
        .and_then(serde_json::Value::as_str)
    {
        envelope["dir"] = serde_json::json!(dir);
        // Remove from the results copy (envelope["results"] is already cloned
        // by the json! macro above so the borrow on `value` is no longer active).
        if let Some(obj) = envelope["results"].as_object_mut() {
            obj.remove("dir");
        }
    }
    envelope
}

/// Format the output envelope for the user.
///
/// - **JSON**: serializes `{"results": ..., "total": <optional>, "hints": [...]}`
/// - **Text**: formats `results` as text, appends hint lines if any, adds pagination notice if needed
#[must_use]
pub fn format_envelope(
    format: Format,
    value: &serde_json::Value,
    total: Option<u64>,
    hints: &[crate::hints::Hint],
) -> String {
    match format {
        Format::Json | Format::Github => {
            let envelope = build_envelope_value(value, total, hints);
            serde_json::to_string_pretty(&envelope)
                .expect("serializing serde_json::Value is infallible")
        }
        Format::Text => {
            let mut cache = JaqFilterCache::new();
            let mut text = format_results_as_text(value, total, &mut cache);
            append_hint_lines(&mut text, hints);
            sanitize_control_chars(&text)
        }
    }
}

/// Format an already-built envelope JSON value.
///
/// Unlike [`format_envelope`], this variant accepts a pre-built envelope (e.g. one that
/// has had `--files-from` counters injected). In JSON mode, the envelope is serialized
/// directly. In text mode, `results_value` (the raw results payload, before envelope
/// wrapping) is used for human-readable formatting.
#[must_use]
pub fn format_prebuilt_envelope(
    format: Format,
    envelope: &serde_json::Value,
    total: Option<u64>,
    hints: &[crate::hints::Hint],
    results_value: &serde_json::Value,
) -> String {
    match format {
        Format::Json | Format::Github => serde_json::to_string_pretty(envelope)
            .expect("serializing serde_json::Value is infallible"),
        Format::Text => {
            let mut cache = JaqFilterCache::new();
            let mut text = format_results_as_text(results_value, total, &mut cache);
            append_hint_lines(&mut text, hints);
            sanitize_control_chars(&text)
        }
    }
}

/// Format results for text output, applying pagination notice and tag-summary header.
///
/// Called by [`format_envelope`] when producing text output. The `total` is the
/// count stored in the envelope (may exceed the number of items in `results`).
fn format_results_as_text(
    results: &serde_json::Value,
    total: Option<u64>,
    cache: &mut JaqFilterCache,
) -> String {
    // Special case: array of tag summary entries ({count, name}) — reconstruct
    // the "N unique tags" header that was previously part of the TAG_SUMMARY_FILTER.
    if let (Some(total), serde_json::Value::Array(arr)) = (total, results) {
        let is_tag_array = !arr.is_empty()
            && arr.iter().all(|v| {
                v.as_object().is_some_and(|m| {
                    m.contains_key("count") && m.contains_key("name") && m.len() == 2
                })
            });
        if is_tag_array {
            let tag_label = if total == 1 { "tag" } else { "tags" };
            let header = format!("{total} unique {tag_label}");
            let entries = format_value_as_text(results, cache);
            let mut out = if entries.is_empty() {
                header
            } else {
                format!("{header}\n{entries}")
            };
            // `tags --limit N` used to print the full unique-tag count in the
            // header and then N rows, with nothing saying the list was cut —
            // the truncation footer every other limited listing carries was
            // skipped by this early return (iter-213, dogfood UX-5).
            let shown = arr.len() as u64;
            if shown < total {
                let _ = write!(out, "\nshowing {shown} of {total} matches");
            }
            return out;
        }
    }

    let mut text = format_value_as_text(results, cache);
    if let Some(fields_line) = find_fields_summary(results) {
        let _ = write!(text, "\n{fields_line}");
    }
    if let Some(total) = total {
        let shown = match results {
            serde_json::Value::Array(arr) => arr.len() as u64,
            _ => return text,
        };
        if shown < total {
            return format!("{text}\nshowing {shown} of {total} matches");
        }
    }
    text
}

/// Every field a `find` result item can carry, in the order the JSON struct
/// declares them. `serde_json::Map` is a `BTreeMap` here (no `preserve_order`
/// feature), so the keys come back alphabetised — this list restores the
/// order a reader expects.
const FIND_FIELD_ORDER: &[&str] = &[
    "file",
    "modified",
    "size",
    "lines",
    "title",
    "properties",
    "properties_typed",
    "tags",
    "sections",
    "tasks",
    "links",
    "backlinks",
];

/// Keys that ride along with a `--fields` field rather than being selectable
/// themselves, so they belong to the FileObject vocabulary but never appear in
/// the `fields:` footer.
///
/// iter-267 (DEC-283): `title_source` is emitted whenever `title` is, and
/// naming it in the footer would imply `--fields title_source` works.
///
/// iter-274 (BUG-27): `matches` and `score` joined it. Both ride along with a
/// body search and neither is selectable — `--fields score` is rejected with
/// "unknown field" — so listing them in a footer that reads as the `--fields`
/// vocabulary broke the DEC-275 round-trip promise: everything the footer
/// names must be nameable back.
const FIND_COMPANION_KEYS: &[&str] = &["title_source", "matches", "score"];

/// The `fields:` footer under a `--format text` find listing (iter-252).
///
/// The default result shape omits `sections`, `links`, `tasks`, `backlinks`
/// and `properties-typed`, and a reader cannot tell an omitted field from an
/// empty one. Naming what is present — and what `--fields all` would add —
/// makes the shape self-describing without a round trip.
///
/// iter-254: with an explicit `--fields` now an exact projection, the line
/// also reports which of `modified`/`size`/`lines` a projection dropped, so
/// the rule ("without `--fields`: the seven default keys; with `--fields`:
/// exactly the named fields plus `file`") is legible from the output itself.
///
/// `None` for anything that is not a non-empty array of find result items
/// (detected the same way the text renderer detects a `FileObject`: a `file`
/// key and no key outside the `FileObject` vocabulary).
fn find_fields_summary(results: &serde_json::Value) -> Option<String> {
    let arr = results.as_array()?;
    let first = arr.first()?.as_object()?;
    if !first.contains_key("file")
        || !first.keys().all(|k| {
            FIND_FIELD_ORDER.contains(&k.as_str()) || FIND_COMPANION_KEYS.contains(&k.as_str())
        })
    {
        return None;
    }
    let present: Vec<&str> = FIND_FIELD_ORDER
        .iter()
        .copied()
        .filter(|k| first.contains_key(*k))
        .collect();
    let missing: Vec<&str> = FIND_FIELD_ORDER
        .iter()
        .copied()
        .filter(|k| !first.contains_key(*k) && *k != "properties_typed")
        .collect();
    let mut line = format!("fields: {}", present.join(", "));
    if !missing.is_empty() {
        let _ = write!(line, " (--fields all adds {})", missing.join(", "));
    }
    Some(line)
}

/// Format an error for output to stderr.
#[must_use]
pub fn format_error(
    format: Format,
    error: &str,
    path: Option<&str>,
    hint: Option<&str>,
    cause: Option<&str>,
) -> String {
    match format {
        Format::Json | Format::Github => {
            let mut obj = json!({"error": error});
            if let Some(p) = path {
                obj["path"] = json!(p);
            }
            if let Some(h) = hint {
                obj["hint"] = json!(h);
            }
            if let Some(c) = cause {
                obj["cause"] = json!(c);
            }
            serde_json::to_string_pretty(&obj).expect("serializing serde_json::Value is infallible")
        }
        Format::Text => {
            // iter-267 (UX-18): lowercase `error:`, matching clap's own parse
            // errors and the Rust CLI convention. The two prefixes used to
            // disagree inside a single session's scrollback.
            let mut msg = format!("error: {error}");
            if let Some(p) = path {
                let _ = write!(msg, "\n  path: {p}");
            }
            if let Some(h) = hint {
                let _ = write!(msg, "\n  hint: {h}");
            }
            if let Some(c) = cause {
                let _ = write!(msg, "\n  cause: {c}");
            }
            sanitize_control_chars(&msg)
        }
    }
}

/// Format a structured error for a frontmatter size-budget violation.
///
/// JSON shape:
/// ```json
/// {"error": "frontmatter would exceed size budget", "limit_bytes": N, "would_be_bytes": M,
///  "limit_lines": L, "would_be_lines": K, "file": "path"}
/// ```
///
/// Text shape mirrors the JSON fields for readability in a terminal. The `file`
/// field is sanitized for control characters since it is path-derived.
#[must_use]
pub fn format_budget_error(
    format: Format,
    e: &hyalo_core::frontmatter::FrontmatterBudgetError,
) -> String {
    let safe_file = sanitize_control_chars(&e.file);
    match format {
        Format::Json | Format::Github => {
            let obj = serde_json::json!({
                "error": "frontmatter would exceed size budget",
                "limit_bytes": e.limit_bytes,
                "would_be_bytes": e.would_be_bytes,
                "limit_lines": e.limit_lines,
                "would_be_lines": e.would_be_lines,
                "file": safe_file,
            });
            serde_json::to_string_pretty(&obj).expect("serializing serde_json::Value is infallible")
        }
        Format::Text => {
            format!(
                "error: frontmatter would exceed size budget\n  file: {}\n  would_be_bytes: {} (limit {})\n  would_be_lines: {} (limit {})",
                safe_file, e.would_be_bytes, e.limit_bytes, e.would_be_lines, e.limit_lines
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Submodules (iteration 247)
// ---------------------------------------------------------------------------
//
// `output.rs` had grown to 3,744 lines -- a review hotspot flagged by the
// 2026-08-27 deep review. It is split along the pipeline: the static filter
// table, the jq engine, the dynamic file-object filter, and the hand-written
// text renderings. This file keeps the envelope and the `Format` /
// `CommandOutcome` vocabulary every command speaks.

mod file_object;
mod filters;
mod jq;
mod text;
mod text_generators;
mod text_lint;
mod text_types;

// Glob re-exports: each item keeps the visibility it had before the split (a
// glob re-export cannot widen it), and this is also how the submodules reach
// each other, since each one imports this parent.
use file_object::build_file_object_filter;
pub(crate) use file_object::set_broken_links_only;
use filters::{key_signature, lookup_filter};
pub use jq::*;
use text::format_value_as_text;
use text_generators::format_generator_output_text;
use text_lint::{
    format_lint_fix_output_text, format_lint_output_text, format_lint_rules_list_text,
    format_lint_rules_mutation_text,
};
use text_types::{format_type_list_entry_text, format_type_show_text};

#[cfg(test)]
mod tests;
